/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * BFIN API
 * Banking Finance API - Sistema de gestão financeira pessoal
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV1CashFlowMonthly200, GetApiV1CashFlowMonthlyParams } from '../api.schemas';

import { customInstance } from '.././custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getCashFlow = () => {
  /**
 * Retorna o saldo projetado para cada dia do mês informado.

- **Mês passado**: reconstruído a partir do histórico real (balance_history)
- **Mês atual**: dias passados = histórico real, dias futuros = projeção
- **Mês futuro**: simulação completa a partir do saldo atual

**Algoritmo por dia:**
1. Aplica receitas pendentes com vencimento neste dia
2. Aplica despesas pendentes com vencimento neste dia
3. Se sobrou saldo positivo e há dívidas flutuantes:
   abate `min(saldo, dívida)` — nunca mais do que o disponível

**Dívidas flutuantes** são despesas criadas com `isFloating: true` (sem data de vencimento).
Elas aparecem em `totalFloatingDebt` e são abatidas automaticamente no dia em que
houver excedente, até zerarem.

**Receitas recorrentes** agendadas (criadas com `isRecurring: true` e data futura)
geram instâncias pendentes automaticamente e aparecem na projeção.

 * @summary Projeção de saldo mensal dia a dia
 */
  const getApiV1CashFlowMonthly = (
    params: GetApiV1CashFlowMonthlyParams,
    options?: SecondParameter<typeof customInstance<GetApiV1CashFlowMonthly200>>
  ) => {
    return customInstance<GetApiV1CashFlowMonthly200>(
      { url: `/api/v1/cash-flow/monthly`, method: 'GET', params },
      options
    );
  };
  return { getApiV1CashFlowMonthly };
};
export type GetApiV1CashFlowMonthlyResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCashFlow>['getApiV1CashFlowMonthly']>>
>;
