/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * BFIN API
 * Banking Finance API - Sistema de gestão financeira pessoal
 * OpenAPI spec version: 1.0.0
 */
import type {
  DeleteApiV1TransactionsId200,
  GetApiV1Transactions200,
  GetApiV1TransactionsParams,
  PostApiV1TransactionsExpenseBody,
  PostApiV1TransactionsIdMarkAsPaid200,
  PostApiV1TransactionsIncomeBody,
  PostApiV1TransactionsTransfer201,
  PostApiV1TransactionsTransferBody,
  PutApiV1TransactionsId200,
  PutApiV1TransactionsIdBody,
  Transaction,
} from '../api.schemas';

import { customInstance } from '.././custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getTransactions = () => {
  /**
   * Processa uma receita aplicando regras automáticas (30/70 - reserva de emergência e saldo disponível)
   * @summary Criar receita
   */
  const postApiV1TransactionsIncome = (
    postApiV1TransactionsIncomeBody: PostApiV1TransactionsIncomeBody,
    options?: SecondParameter<typeof customInstance<Transaction>>
  ) => {
    return customInstance<Transaction>(
      {
        url: `/api/v1/transactions/income`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: postApiV1TransactionsIncomeBody,
      },
      options
    );
  };
  /**
   * Cria uma despesa. Tipo "fixed" bloqueia o valor no saldo (pode ser recorrente). Tipo "variable" debita imediatamente.
   * @summary Criar despesa (fixa ou variável)
   */
  const postApiV1TransactionsExpense = (
    postApiV1TransactionsExpenseBody: PostApiV1TransactionsExpenseBody,
    options?: SecondParameter<typeof customInstance<Transaction>>
  ) => {
    return customInstance<Transaction>(
      {
        url: `/api/v1/transactions/expense`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: postApiV1TransactionsExpenseBody,
      },
      options
    );
  };
  /**
   * Lista transações do usuário com filtros opcionais (conta, tipo, status, data, categoria, paginação)
   * @summary Listar transações
   */
  const getApiV1Transactions = (
    params?: GetApiV1TransactionsParams,
    options?: SecondParameter<typeof customInstance<GetApiV1Transactions200>>
  ) => {
    return customInstance<GetApiV1Transactions200>(
      { url: `/api/v1/transactions`, method: 'GET', params },
      options
    );
  };
  /**
   * Retorna detalhes de uma transação específica
   * @summary Obter transação por ID
   */
  const getApiV1TransactionsId = (
    id: string,
    options?: SecondParameter<typeof customInstance<Transaction>>
  ) => {
    return customInstance<Transaction>(
      { url: `/api/v1/transactions/${id}`, method: 'GET' },
      options
    );
  };
  /**
   * Atualiza uma transação (apenas se estiver com status pending ou locked)
   * @summary Atualizar transação
   */
  const putApiV1TransactionsId = (
    id: string,
    putApiV1TransactionsIdBody: PutApiV1TransactionsIdBody,
    options?: SecondParameter<typeof customInstance<PutApiV1TransactionsId200>>
  ) => {
    return customInstance<PutApiV1TransactionsId200>(
      {
        url: `/api/v1/transactions/${id}`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: putApiV1TransactionsIdBody,
      },
      options
    );
  };
  /**
   * Deleta uma transação (apenas se estiver com status pending ou locked)
   * @summary Deletar transação
   */
  const deleteApiV1TransactionsId = (
    id: string,
    options?: SecondParameter<typeof customInstance<DeleteApiV1TransactionsId200>>
  ) => {
    return customInstance<DeleteApiV1TransactionsId200>(
      { url: `/api/v1/transactions/${id}`, method: 'DELETE' },
      options
    );
  };
  /**
   * Marca uma despesa fixa como paga, executando o pagamento e debitando o valor do saldo disponível
   * @summary Marcar despesa fixa como paga
   */
  const postApiV1TransactionsIdMarkAsPaid = (
    id: string,
    options?: SecondParameter<typeof customInstance<PostApiV1TransactionsIdMarkAsPaid200>>
  ) => {
    return customInstance<PostApiV1TransactionsIdMarkAsPaid200>(
      { url: `/api/v1/transactions/${id}/mark-as-paid`, method: 'POST' },
      options
    );
  };
  /**
   * Cria uma nova transação com os mesmos dados da transação original (com descrição modificada)
   * @summary Duplicar transação
   */
  const postApiV1TransactionsIdDuplicate = (
    id: string,
    options?: SecondParameter<typeof customInstance<Transaction>>
  ) => {
    return customInstance<Transaction>(
      { url: `/api/v1/transactions/${id}/duplicate`, method: 'POST' },
      options
    );
  };
  /**
   * Realiza transferência de valor da conta de origem para conta de destino. Apenas o saldo disponível (available_balance) pode ser transferido.
   * @summary Transferir valor entre contas
   */
  const postApiV1TransactionsTransfer = (
    postApiV1TransactionsTransferBody: PostApiV1TransactionsTransferBody,
    options?: SecondParameter<typeof customInstance<PostApiV1TransactionsTransfer201>>
  ) => {
    return customInstance<PostApiV1TransactionsTransfer201>(
      {
        url: `/api/v1/transactions/transfer`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: postApiV1TransactionsTransferBody,
      },
      options
    );
  };
  return {
    postApiV1TransactionsIncome,
    postApiV1TransactionsExpense,
    getApiV1Transactions,
    getApiV1TransactionsId,
    putApiV1TransactionsId,
    deleteApiV1TransactionsId,
    postApiV1TransactionsIdMarkAsPaid,
    postApiV1TransactionsIdDuplicate,
    postApiV1TransactionsTransfer,
  };
};
export type PostApiV1TransactionsIncomeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTransactions>['postApiV1TransactionsIncome']>>
>;
export type PostApiV1TransactionsExpenseResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTransactions>['postApiV1TransactionsExpense']>>
>;
export type GetApiV1TransactionsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTransactions>['getApiV1Transactions']>>
>;
export type GetApiV1TransactionsIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTransactions>['getApiV1TransactionsId']>>
>;
export type PutApiV1TransactionsIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTransactions>['putApiV1TransactionsId']>>
>;
export type DeleteApiV1TransactionsIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTransactions>['deleteApiV1TransactionsId']>>
>;
export type PostApiV1TransactionsIdMarkAsPaidResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTransactions>['postApiV1TransactionsIdMarkAsPaid']>>
>;
export type PostApiV1TransactionsIdDuplicateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTransactions>['postApiV1TransactionsIdDuplicate']>>
>;
export type PostApiV1TransactionsTransferResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTransactions>['postApiV1TransactionsTransfer']>>
>;
