/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BFIN API
 * Banking Finance API - Sistema de gestão financeira pessoal
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type { Arguments, Key, SWRConfiguration } from 'swr';

import useSWRMutation from 'swr/mutation';
import type { SWRMutationConfiguration } from 'swr/mutation';

import type {
  DeleteApiV1TransactionsId200,
  Error,
  GetApiV1Transactions200,
  GetApiV1TransactionsParams,
  PostApiV1TransactionsFixedExpenseBody,
  PostApiV1TransactionsIdMarkAsPaid200,
  PostApiV1TransactionsIncomeBody,
  PostApiV1TransactionsVariableExpenseBody,
  PutApiV1TransactionsId200,
  PutApiV1TransactionsIdBody,
  Transaction,
} from '../hooks.schemas';

import { customInstance } from '../../client/custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Processa uma receita aplicando regras automáticas (30/70 - reserva de emergência e saldo disponível)
 * @summary Criar receita
 */
export const postApiV1TransactionsIncome = (
  postApiV1TransactionsIncomeBody: PostApiV1TransactionsIncomeBody,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<Transaction>(
    {
      url: `/api/v1/transactions/income`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: postApiV1TransactionsIncomeBody,
    },
    options
  );
};

export const getPostApiV1TransactionsIncomeMutationFetcher = (
  options?: SecondParameter<typeof customInstance>
) => {
  return (_: Key, { arg }: { arg: PostApiV1TransactionsIncomeBody }) => {
    return postApiV1TransactionsIncome(arg, options);
  };
};
export const getPostApiV1TransactionsIncomeMutationKey = () =>
  [`/api/v1/transactions/income`] as const;

export type PostApiV1TransactionsIncomeMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1TransactionsIncome>>
>;
export type PostApiV1TransactionsIncomeMutationError = Error | void | void | void;

/**
 * @summary Criar receita
 */
export const usePostApiV1TransactionsIncome = <TError = Error | void | void | void>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postApiV1TransactionsIncome>>,
    TError,
    Key,
    PostApiV1TransactionsIncomeBody,
    Awaited<ReturnType<typeof postApiV1TransactionsIncome>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostApiV1TransactionsIncomeMutationKey();
  const swrFn = getPostApiV1TransactionsIncomeMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
/**
 * Cria uma despesa fixa com bloqueio preventivo do valor no saldo disponível
 * @summary Criar despesa fixa
 */
export const postApiV1TransactionsFixedExpense = (
  postApiV1TransactionsFixedExpenseBody: PostApiV1TransactionsFixedExpenseBody,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<Transaction>(
    {
      url: `/api/v1/transactions/fixed-expense`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: postApiV1TransactionsFixedExpenseBody,
    },
    options
  );
};

export const getPostApiV1TransactionsFixedExpenseMutationFetcher = (
  options?: SecondParameter<typeof customInstance>
) => {
  return (_: Key, { arg }: { arg: PostApiV1TransactionsFixedExpenseBody }) => {
    return postApiV1TransactionsFixedExpense(arg, options);
  };
};
export const getPostApiV1TransactionsFixedExpenseMutationKey = () =>
  [`/api/v1/transactions/fixed-expense`] as const;

export type PostApiV1TransactionsFixedExpenseMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1TransactionsFixedExpense>>
>;
export type PostApiV1TransactionsFixedExpenseMutationError = Error | void | void | void;

/**
 * @summary Criar despesa fixa
 */
export const usePostApiV1TransactionsFixedExpense = <
  TError = Error | void | void | void,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postApiV1TransactionsFixedExpense>>,
    TError,
    Key,
    PostApiV1TransactionsFixedExpenseBody,
    Awaited<ReturnType<typeof postApiV1TransactionsFixedExpense>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostApiV1TransactionsFixedExpenseMutationKey();
  const swrFn = getPostApiV1TransactionsFixedExpenseMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
/**
 * Cria uma despesa variável com débito imediato no saldo disponível
 * @summary Criar despesa variável
 */
export const postApiV1TransactionsVariableExpense = (
  postApiV1TransactionsVariableExpenseBody: PostApiV1TransactionsVariableExpenseBody,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<Transaction>(
    {
      url: `/api/v1/transactions/variable-expense`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: postApiV1TransactionsVariableExpenseBody,
    },
    options
  );
};

export const getPostApiV1TransactionsVariableExpenseMutationFetcher = (
  options?: SecondParameter<typeof customInstance>
) => {
  return (_: Key, { arg }: { arg: PostApiV1TransactionsVariableExpenseBody }) => {
    return postApiV1TransactionsVariableExpense(arg, options);
  };
};
export const getPostApiV1TransactionsVariableExpenseMutationKey = () =>
  [`/api/v1/transactions/variable-expense`] as const;

export type PostApiV1TransactionsVariableExpenseMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1TransactionsVariableExpense>>
>;
export type PostApiV1TransactionsVariableExpenseMutationError = Error | void | void | void;

/**
 * @summary Criar despesa variável
 */
export const usePostApiV1TransactionsVariableExpense = <
  TError = Error | void | void | void,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postApiV1TransactionsVariableExpense>>,
    TError,
    Key,
    PostApiV1TransactionsVariableExpenseBody,
    Awaited<ReturnType<typeof postApiV1TransactionsVariableExpense>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostApiV1TransactionsVariableExpenseMutationKey();
  const swrFn = getPostApiV1TransactionsVariableExpenseMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
/**
 * Lista transações do usuário com filtros opcionais (conta, tipo, status, data, categoria, paginação)
 * @summary Listar transações
 */
export const getApiV1Transactions = (
  params?: GetApiV1TransactionsParams,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<GetApiV1Transactions200>(
    { url: `/api/v1/transactions`, method: 'GET', params },
    options
  );
};

export const getGetApiV1TransactionsKey = (params?: GetApiV1TransactionsParams) =>
  [`/api/v1/transactions`, ...(params ? [params] : [])] as const;

export type GetApiV1TransactionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1Transactions>>
>;
export type GetApiV1TransactionsQueryError = void;

/**
 * @summary Listar transações
 */
export const useGetApiV1Transactions = <TError = void>(
  params?: GetApiV1TransactionsParams,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getApiV1Transactions>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetApiV1TransactionsKey(params) : null));
  const swrFn = () => getApiV1Transactions(params, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
/**
 * Retorna detalhes de uma transação específica
 * @summary Obter transação por ID
 */
export const getApiV1TransactionsId = (
  id: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<Transaction>({ url: `/api/v1/transactions/${id}`, method: 'GET' }, options);
};

export const getGetApiV1TransactionsIdKey = (id: string) => [`/api/v1/transactions/${id}`] as const;

export type GetApiV1TransactionsIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1TransactionsId>>
>;
export type GetApiV1TransactionsIdQueryError = void | void | void;

/**
 * @summary Obter transação por ID
 */
export const useGetApiV1TransactionsId = <TError = void | void | void>(
  id: string,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getApiV1TransactionsId>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && !!id;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetApiV1TransactionsIdKey(id) : null));
  const swrFn = () => getApiV1TransactionsId(id, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
/**
 * Atualiza uma transação (apenas se estiver com status pending ou locked)
 * @summary Atualizar transação
 */
export const putApiV1TransactionsId = (
  id: string,
  putApiV1TransactionsIdBody: PutApiV1TransactionsIdBody,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<PutApiV1TransactionsId200>(
    {
      url: `/api/v1/transactions/${id}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: putApiV1TransactionsIdBody,
    },
    options
  );
};

export const getPutApiV1TransactionsIdMutationFetcher = (
  id: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return (_: Key, { arg }: { arg: PutApiV1TransactionsIdBody }) => {
    return putApiV1TransactionsId(id, arg, options);
  };
};
export const getPutApiV1TransactionsIdMutationKey = (id: string) =>
  [`/api/v1/transactions/${id}`] as const;

export type PutApiV1TransactionsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putApiV1TransactionsId>>
>;
export type PutApiV1TransactionsIdMutationError = Error | void | void | void;

/**
 * @summary Atualizar transação
 */
export const usePutApiV1TransactionsId = <TError = Error | void | void | void>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof putApiV1TransactionsId>>,
      TError,
      Key,
      PutApiV1TransactionsIdBody,
      Awaited<ReturnType<typeof putApiV1TransactionsId>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPutApiV1TransactionsIdMutationKey(id);
  const swrFn = getPutApiV1TransactionsIdMutationFetcher(id, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
/**
 * Deleta uma transação (apenas se estiver com status pending ou locked)
 * @summary Deletar transação
 */
export const deleteApiV1TransactionsId = (
  id: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<DeleteApiV1TransactionsId200>(
    { url: `/api/v1/transactions/${id}`, method: 'DELETE' },
    options
  );
};

export const getDeleteApiV1TransactionsIdMutationFetcher = (
  id: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteApiV1TransactionsId(id, options);
  };
};
export const getDeleteApiV1TransactionsIdMutationKey = (id: string) =>
  [`/api/v1/transactions/${id}`] as const;

export type DeleteApiV1TransactionsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiV1TransactionsId>>
>;
export type DeleteApiV1TransactionsIdMutationError = Error | void | void | void;

/**
 * @summary Deletar transação
 */
export const useDeleteApiV1TransactionsId = <TError = Error | void | void | void>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof deleteApiV1TransactionsId>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof deleteApiV1TransactionsId>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getDeleteApiV1TransactionsIdMutationKey(id);
  const swrFn = getDeleteApiV1TransactionsIdMutationFetcher(id, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
/**
 * Marca uma despesa fixa como paga, executando o pagamento e debitando o valor do saldo disponível
 * @summary Marcar despesa fixa como paga
 */
export const postApiV1TransactionsIdMarkAsPaid = (
  id: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<PostApiV1TransactionsIdMarkAsPaid200>(
    { url: `/api/v1/transactions/${id}/mark-as-paid`, method: 'POST' },
    options
  );
};

export const getPostApiV1TransactionsIdMarkAsPaidMutationFetcher = (
  id: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return (_: Key, __: { arg: Arguments }) => {
    return postApiV1TransactionsIdMarkAsPaid(id, options);
  };
};
export const getPostApiV1TransactionsIdMarkAsPaidMutationKey = (id: string) =>
  [`/api/v1/transactions/${id}/mark-as-paid`] as const;

export type PostApiV1TransactionsIdMarkAsPaidMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1TransactionsIdMarkAsPaid>>
>;
export type PostApiV1TransactionsIdMarkAsPaidMutationError = Error | void | void | void;

/**
 * @summary Marcar despesa fixa como paga
 */
export const usePostApiV1TransactionsIdMarkAsPaid = <TError = Error | void | void | void>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof postApiV1TransactionsIdMarkAsPaid>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof postApiV1TransactionsIdMarkAsPaid>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostApiV1TransactionsIdMarkAsPaidMutationKey(id);
  const swrFn = getPostApiV1TransactionsIdMarkAsPaidMutationFetcher(id, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
/**
 * Cria uma nova transação com os mesmos dados da transação original (com descrição modificada)
 * @summary Duplicar transação
 */
export const postApiV1TransactionsIdDuplicate = (
  id: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<Transaction>(
    { url: `/api/v1/transactions/${id}/duplicate`, method: 'POST' },
    options
  );
};

export const getPostApiV1TransactionsIdDuplicateMutationFetcher = (
  id: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return (_: Key, __: { arg: Arguments }) => {
    return postApiV1TransactionsIdDuplicate(id, options);
  };
};
export const getPostApiV1TransactionsIdDuplicateMutationKey = (id: string) =>
  [`/api/v1/transactions/${id}/duplicate`] as const;

export type PostApiV1TransactionsIdDuplicateMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1TransactionsIdDuplicate>>
>;
export type PostApiV1TransactionsIdDuplicateMutationError = Error | void | void | void;

/**
 * @summary Duplicar transação
 */
export const usePostApiV1TransactionsIdDuplicate = <TError = Error | void | void | void>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof postApiV1TransactionsIdDuplicate>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof postApiV1TransactionsIdDuplicate>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostApiV1TransactionsIdDuplicateMutationKey(id);
  const swrFn = getPostApiV1TransactionsIdDuplicateMutationFetcher(id, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
