/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * BFIN API
 * Banking Finance API - Sistema de gestão financeira pessoal
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type { Arguments, Key, SWRConfiguration } from 'swr';

import useSWRMutation from 'swr/mutation';
import type { SWRMutationConfiguration } from 'swr/mutation';

import type {
  DeleteApiV1TransactionsId200,
  Error,
  GetApiV1Transactions200,
  GetApiV1TransactionsParams,
  PostApiV1TransactionsExpenseBody,
  PostApiV1TransactionsIdMarkAsPaid200,
  PostApiV1TransactionsIncomeBody,
  PostApiV1TransactionsTransfer201,
  PostApiV1TransactionsTransferBody,
  PutApiV1TransactionsId200,
  PutApiV1TransactionsIdBody,
  Transaction,
} from '../hooks.schemas';

import { customInstance } from '../../client/custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Processa uma receita aplicando regras automáticas (30/70 - reserva de emergência e saldo disponível)
 * @summary Criar receita
 */
export type postApiV1TransactionsIncomeResponse201 = {
  data: Transaction;
  status: 201;
};

export type postApiV1TransactionsIncomeResponse400 = {
  data: Error;
  status: 400;
};

export type postApiV1TransactionsIncomeResponse401 = {
  data: void;
  status: 401;
};

export type postApiV1TransactionsIncomeResponse403 = {
  data: void;
  status: 403;
};

export type postApiV1TransactionsIncomeResponse404 = {
  data: void;
  status: 404;
};

export type postApiV1TransactionsIncomeResponseSuccess = postApiV1TransactionsIncomeResponse201 & {
  headers: Headers;
};
export type postApiV1TransactionsIncomeResponseError = (
  | postApiV1TransactionsIncomeResponse400
  | postApiV1TransactionsIncomeResponse401
  | postApiV1TransactionsIncomeResponse403
  | postApiV1TransactionsIncomeResponse404
) & {
  headers: Headers;
};

export type postApiV1TransactionsIncomeResponse =
  | postApiV1TransactionsIncomeResponseSuccess
  | postApiV1TransactionsIncomeResponseError;

export const getPostApiV1TransactionsIncomeUrl = () => {
  return `/api/v1/transactions/income`;
};

export const postApiV1TransactionsIncome = async (
  postApiV1TransactionsIncomeBody: PostApiV1TransactionsIncomeBody,
  options?: RequestInit
): Promise<postApiV1TransactionsIncomeResponse> => {
  return customInstance<postApiV1TransactionsIncomeResponse>(getPostApiV1TransactionsIncomeUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postApiV1TransactionsIncomeBody),
  });
};

export const getPostApiV1TransactionsIncomeMutationFetcher = (
  options?: SecondParameter<typeof customInstance>
) => {
  return (_: Key, { arg }: { arg: PostApiV1TransactionsIncomeBody }) => {
    return postApiV1TransactionsIncome(arg, options);
  };
};
export const getPostApiV1TransactionsIncomeMutationKey = () =>
  [`/api/v1/transactions/income`] as const;

export type PostApiV1TransactionsIncomeMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1TransactionsIncome>>
>;

/**
 * @summary Criar receita
 */
export const usePostApiV1TransactionsIncome = <TError = Error | void>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postApiV1TransactionsIncome>>,
    TError,
    Key,
    PostApiV1TransactionsIncomeBody,
    Awaited<ReturnType<typeof postApiV1TransactionsIncome>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostApiV1TransactionsIncomeMutationKey();
  const swrFn = getPostApiV1TransactionsIncomeMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
/**
 * Cria uma despesa. Tipo "fixed" bloqueia o valor no saldo (pode ser recorrente). Tipo "variable" debita imediatamente.
 * @summary Criar despesa (fixa ou variável)
 */
export type postApiV1TransactionsExpenseResponse201 = {
  data: Transaction;
  status: 201;
};

export type postApiV1TransactionsExpenseResponse400 = {
  data: Error;
  status: 400;
};

export type postApiV1TransactionsExpenseResponse401 = {
  data: void;
  status: 401;
};

export type postApiV1TransactionsExpenseResponse403 = {
  data: void;
  status: 403;
};

export type postApiV1TransactionsExpenseResponse404 = {
  data: void;
  status: 404;
};

export type postApiV1TransactionsExpenseResponseSuccess =
  postApiV1TransactionsExpenseResponse201 & {
    headers: Headers;
  };
export type postApiV1TransactionsExpenseResponseError = (
  | postApiV1TransactionsExpenseResponse400
  | postApiV1TransactionsExpenseResponse401
  | postApiV1TransactionsExpenseResponse403
  | postApiV1TransactionsExpenseResponse404
) & {
  headers: Headers;
};

export type postApiV1TransactionsExpenseResponse =
  | postApiV1TransactionsExpenseResponseSuccess
  | postApiV1TransactionsExpenseResponseError;

export const getPostApiV1TransactionsExpenseUrl = () => {
  return `/api/v1/transactions/expense`;
};

export const postApiV1TransactionsExpense = async (
  postApiV1TransactionsExpenseBody: PostApiV1TransactionsExpenseBody,
  options?: RequestInit
): Promise<postApiV1TransactionsExpenseResponse> => {
  return customInstance<postApiV1TransactionsExpenseResponse>(
    getPostApiV1TransactionsExpenseUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(postApiV1TransactionsExpenseBody),
    }
  );
};

export const getPostApiV1TransactionsExpenseMutationFetcher = (
  options?: SecondParameter<typeof customInstance>
) => {
  return (_: Key, { arg }: { arg: PostApiV1TransactionsExpenseBody }) => {
    return postApiV1TransactionsExpense(arg, options);
  };
};
export const getPostApiV1TransactionsExpenseMutationKey = () =>
  [`/api/v1/transactions/expense`] as const;

export type PostApiV1TransactionsExpenseMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1TransactionsExpense>>
>;

/**
 * @summary Criar despesa (fixa ou variável)
 */
export const usePostApiV1TransactionsExpense = <TError = Error | void>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postApiV1TransactionsExpense>>,
    TError,
    Key,
    PostApiV1TransactionsExpenseBody,
    Awaited<ReturnType<typeof postApiV1TransactionsExpense>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostApiV1TransactionsExpenseMutationKey();
  const swrFn = getPostApiV1TransactionsExpenseMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
/**
 * Lista transações do usuário com filtros opcionais (conta, tipo, status, data, categoria, paginação)
 * @summary Listar transações
 */
export type getApiV1TransactionsResponse200 = {
  data: GetApiV1Transactions200;
  status: 200;
};

export type getApiV1TransactionsResponse401 = {
  data: void;
  status: 401;
};

export type getApiV1TransactionsResponseSuccess = getApiV1TransactionsResponse200 & {
  headers: Headers;
};
export type getApiV1TransactionsResponseError = getApiV1TransactionsResponse401 & {
  headers: Headers;
};

export type getApiV1TransactionsResponse =
  | getApiV1TransactionsResponseSuccess
  | getApiV1TransactionsResponseError;

export const getGetApiV1TransactionsUrl = (params?: GetApiV1TransactionsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/transactions?${stringifiedParams}`
    : `/api/v1/transactions`;
};

export const getApiV1Transactions = async (
  params?: GetApiV1TransactionsParams,
  options?: RequestInit
): Promise<getApiV1TransactionsResponse> => {
  return customInstance<getApiV1TransactionsResponse>(getGetApiV1TransactionsUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getGetApiV1TransactionsKey = (params?: GetApiV1TransactionsParams) =>
  [`/api/v1/transactions`, ...(params ? [params] : [])] as const;

export type GetApiV1TransactionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1Transactions>>
>;

/**
 * @summary Listar transações
 */
export const useGetApiV1Transactions = <TError = void>(
  params?: GetApiV1TransactionsParams,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getApiV1Transactions>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetApiV1TransactionsKey(params) : null));
  const swrFn = () => getApiV1Transactions(params, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
/**
 * Retorna detalhes de uma transação específica
 * @summary Obter transação por ID
 */
export type getApiV1TransactionsIdResponse200 = {
  data: Transaction;
  status: 200;
};

export type getApiV1TransactionsIdResponse401 = {
  data: void;
  status: 401;
};

export type getApiV1TransactionsIdResponse403 = {
  data: void;
  status: 403;
};

export type getApiV1TransactionsIdResponse404 = {
  data: void;
  status: 404;
};

export type getApiV1TransactionsIdResponseSuccess = getApiV1TransactionsIdResponse200 & {
  headers: Headers;
};
export type getApiV1TransactionsIdResponseError = (
  | getApiV1TransactionsIdResponse401
  | getApiV1TransactionsIdResponse403
  | getApiV1TransactionsIdResponse404
) & {
  headers: Headers;
};

export type getApiV1TransactionsIdResponse =
  | getApiV1TransactionsIdResponseSuccess
  | getApiV1TransactionsIdResponseError;

export const getGetApiV1TransactionsIdUrl = (id: string) => {
  return `/api/v1/transactions/${id}`;
};

export const getApiV1TransactionsId = async (
  id: string,
  options?: RequestInit
): Promise<getApiV1TransactionsIdResponse> => {
  return customInstance<getApiV1TransactionsIdResponse>(getGetApiV1TransactionsIdUrl(id), {
    ...options,
    method: 'GET',
  });
};

export const getGetApiV1TransactionsIdKey = (id: string) => [`/api/v1/transactions/${id}`] as const;

export type GetApiV1TransactionsIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1TransactionsId>>
>;

/**
 * @summary Obter transação por ID
 */
export const useGetApiV1TransactionsId = <TError = void>(
  id: string,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getApiV1TransactionsId>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && !!id;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetApiV1TransactionsIdKey(id) : null));
  const swrFn = () => getApiV1TransactionsId(id, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
/**
 * Atualiza uma transação (apenas se estiver com status pending ou locked)
 * @summary Atualizar transação
 */
export type putApiV1TransactionsIdResponse200 = {
  data: PutApiV1TransactionsId200;
  status: 200;
};

export type putApiV1TransactionsIdResponse400 = {
  data: Error;
  status: 400;
};

export type putApiV1TransactionsIdResponse401 = {
  data: void;
  status: 401;
};

export type putApiV1TransactionsIdResponse403 = {
  data: void;
  status: 403;
};

export type putApiV1TransactionsIdResponse404 = {
  data: void;
  status: 404;
};

export type putApiV1TransactionsIdResponseSuccess = putApiV1TransactionsIdResponse200 & {
  headers: Headers;
};
export type putApiV1TransactionsIdResponseError = (
  | putApiV1TransactionsIdResponse400
  | putApiV1TransactionsIdResponse401
  | putApiV1TransactionsIdResponse403
  | putApiV1TransactionsIdResponse404
) & {
  headers: Headers;
};

export type putApiV1TransactionsIdResponse =
  | putApiV1TransactionsIdResponseSuccess
  | putApiV1TransactionsIdResponseError;

export const getPutApiV1TransactionsIdUrl = (id: string) => {
  return `/api/v1/transactions/${id}`;
};

export const putApiV1TransactionsId = async (
  id: string,
  putApiV1TransactionsIdBody: PutApiV1TransactionsIdBody,
  options?: RequestInit
): Promise<putApiV1TransactionsIdResponse> => {
  return customInstance<putApiV1TransactionsIdResponse>(getPutApiV1TransactionsIdUrl(id), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(putApiV1TransactionsIdBody),
  });
};

export const getPutApiV1TransactionsIdMutationFetcher = (
  id: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return (_: Key, { arg }: { arg: PutApiV1TransactionsIdBody }) => {
    return putApiV1TransactionsId(id, arg, options);
  };
};
export const getPutApiV1TransactionsIdMutationKey = (id: string) =>
  [`/api/v1/transactions/${id}`] as const;

export type PutApiV1TransactionsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putApiV1TransactionsId>>
>;

/**
 * @summary Atualizar transação
 */
export const usePutApiV1TransactionsId = <TError = Error | void>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof putApiV1TransactionsId>>,
      TError,
      Key,
      PutApiV1TransactionsIdBody,
      Awaited<ReturnType<typeof putApiV1TransactionsId>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPutApiV1TransactionsIdMutationKey(id);
  const swrFn = getPutApiV1TransactionsIdMutationFetcher(id, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
/**
 * Deleta uma transação (apenas se estiver com status pending ou locked)
 * @summary Deletar transação
 */
export type deleteApiV1TransactionsIdResponse200 = {
  data: DeleteApiV1TransactionsId200;
  status: 200;
};

export type deleteApiV1TransactionsIdResponse400 = {
  data: Error;
  status: 400;
};

export type deleteApiV1TransactionsIdResponse401 = {
  data: void;
  status: 401;
};

export type deleteApiV1TransactionsIdResponse403 = {
  data: void;
  status: 403;
};

export type deleteApiV1TransactionsIdResponse404 = {
  data: void;
  status: 404;
};

export type deleteApiV1TransactionsIdResponseSuccess = deleteApiV1TransactionsIdResponse200 & {
  headers: Headers;
};
export type deleteApiV1TransactionsIdResponseError = (
  | deleteApiV1TransactionsIdResponse400
  | deleteApiV1TransactionsIdResponse401
  | deleteApiV1TransactionsIdResponse403
  | deleteApiV1TransactionsIdResponse404
) & {
  headers: Headers;
};

export type deleteApiV1TransactionsIdResponse =
  | deleteApiV1TransactionsIdResponseSuccess
  | deleteApiV1TransactionsIdResponseError;

export const getDeleteApiV1TransactionsIdUrl = (id: string) => {
  return `/api/v1/transactions/${id}`;
};

export const deleteApiV1TransactionsId = async (
  id: string,
  options?: RequestInit
): Promise<deleteApiV1TransactionsIdResponse> => {
  return customInstance<deleteApiV1TransactionsIdResponse>(getDeleteApiV1TransactionsIdUrl(id), {
    ...options,
    method: 'DELETE',
  });
};

export const getDeleteApiV1TransactionsIdMutationFetcher = (
  id: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteApiV1TransactionsId(id, options);
  };
};
export const getDeleteApiV1TransactionsIdMutationKey = (id: string) =>
  [`/api/v1/transactions/${id}`] as const;

export type DeleteApiV1TransactionsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiV1TransactionsId>>
>;

/**
 * @summary Deletar transação
 */
export const useDeleteApiV1TransactionsId = <TError = Error | void>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof deleteApiV1TransactionsId>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof deleteApiV1TransactionsId>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getDeleteApiV1TransactionsIdMutationKey(id);
  const swrFn = getDeleteApiV1TransactionsIdMutationFetcher(id, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
/**
 * Marca uma despesa fixa como paga, executando o pagamento e debitando o valor do saldo disponível
 * @summary Marcar despesa fixa como paga
 */
export type postApiV1TransactionsIdMarkAsPaidResponse200 = {
  data: PostApiV1TransactionsIdMarkAsPaid200;
  status: 200;
};

export type postApiV1TransactionsIdMarkAsPaidResponse400 = {
  data: Error;
  status: 400;
};

export type postApiV1TransactionsIdMarkAsPaidResponse401 = {
  data: void;
  status: 401;
};

export type postApiV1TransactionsIdMarkAsPaidResponse403 = {
  data: void;
  status: 403;
};

export type postApiV1TransactionsIdMarkAsPaidResponse404 = {
  data: void;
  status: 404;
};

export type postApiV1TransactionsIdMarkAsPaidResponseSuccess =
  postApiV1TransactionsIdMarkAsPaidResponse200 & {
    headers: Headers;
  };
export type postApiV1TransactionsIdMarkAsPaidResponseError = (
  | postApiV1TransactionsIdMarkAsPaidResponse400
  | postApiV1TransactionsIdMarkAsPaidResponse401
  | postApiV1TransactionsIdMarkAsPaidResponse403
  | postApiV1TransactionsIdMarkAsPaidResponse404
) & {
  headers: Headers;
};

export type postApiV1TransactionsIdMarkAsPaidResponse =
  | postApiV1TransactionsIdMarkAsPaidResponseSuccess
  | postApiV1TransactionsIdMarkAsPaidResponseError;

export const getPostApiV1TransactionsIdMarkAsPaidUrl = (id: string) => {
  return `/api/v1/transactions/${id}/mark-as-paid`;
};

export const postApiV1TransactionsIdMarkAsPaid = async (
  id: string,
  options?: RequestInit
): Promise<postApiV1TransactionsIdMarkAsPaidResponse> => {
  return customInstance<postApiV1TransactionsIdMarkAsPaidResponse>(
    getPostApiV1TransactionsIdMarkAsPaidUrl(id),
    {
      ...options,
      method: 'POST',
    }
  );
};

export const getPostApiV1TransactionsIdMarkAsPaidMutationFetcher = (
  id: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return (_: Key, __: { arg: Arguments }) => {
    return postApiV1TransactionsIdMarkAsPaid(id, options);
  };
};
export const getPostApiV1TransactionsIdMarkAsPaidMutationKey = (id: string) =>
  [`/api/v1/transactions/${id}/mark-as-paid`] as const;

export type PostApiV1TransactionsIdMarkAsPaidMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1TransactionsIdMarkAsPaid>>
>;

/**
 * @summary Marcar despesa fixa como paga
 */
export const usePostApiV1TransactionsIdMarkAsPaid = <TError = Error | void>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof postApiV1TransactionsIdMarkAsPaid>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof postApiV1TransactionsIdMarkAsPaid>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostApiV1TransactionsIdMarkAsPaidMutationKey(id);
  const swrFn = getPostApiV1TransactionsIdMarkAsPaidMutationFetcher(id, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
/**
 * Marca uma receita com status pending como recebida, aplicando a regra 30/70 e atualizando o saldo
 * @summary Marcar receita agendada como recebida
 */
export type postApiV1TransactionsIdMarkAsReceivedResponse200 = {
  data: void;
  status: 200;
};

export type postApiV1TransactionsIdMarkAsReceivedResponse400 = {
  data: void;
  status: 400;
};

export type postApiV1TransactionsIdMarkAsReceivedResponse404 = {
  data: void;
  status: 404;
};

export type postApiV1TransactionsIdMarkAsReceivedResponseSuccess =
  postApiV1TransactionsIdMarkAsReceivedResponse200 & {
    headers: Headers;
  };
export type postApiV1TransactionsIdMarkAsReceivedResponseError = (
  | postApiV1TransactionsIdMarkAsReceivedResponse400
  | postApiV1TransactionsIdMarkAsReceivedResponse404
) & {
  headers: Headers;
};

export type postApiV1TransactionsIdMarkAsReceivedResponse =
  | postApiV1TransactionsIdMarkAsReceivedResponseSuccess
  | postApiV1TransactionsIdMarkAsReceivedResponseError;

export const getPostApiV1TransactionsIdMarkAsReceivedUrl = (id: string) => {
  return `/api/v1/transactions/${id}/mark-as-received`;
};

export const postApiV1TransactionsIdMarkAsReceived = async (
  id: string,
  options?: RequestInit
): Promise<postApiV1TransactionsIdMarkAsReceivedResponse> => {
  return customInstance<postApiV1TransactionsIdMarkAsReceivedResponse>(
    getPostApiV1TransactionsIdMarkAsReceivedUrl(id),
    {
      ...options,
      method: 'POST',
    }
  );
};

export const getPostApiV1TransactionsIdMarkAsReceivedMutationFetcher = (
  id: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return (_: Key, __: { arg: Arguments }) => {
    return postApiV1TransactionsIdMarkAsReceived(id, options);
  };
};
export const getPostApiV1TransactionsIdMarkAsReceivedMutationKey = (id: string) =>
  [`/api/v1/transactions/${id}/mark-as-received`] as const;

export type PostApiV1TransactionsIdMarkAsReceivedMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1TransactionsIdMarkAsReceived>>
>;

/**
 * @summary Marcar receita agendada como recebida
 */
export const usePostApiV1TransactionsIdMarkAsReceived = <TError = void>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof postApiV1TransactionsIdMarkAsReceived>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof postApiV1TransactionsIdMarkAsReceived>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostApiV1TransactionsIdMarkAsReceivedMutationKey(id);
  const swrFn = getPostApiV1TransactionsIdMarkAsReceivedMutationFetcher(id, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
/**
 * Cria uma nova transação com os mesmos dados da transação original (com descrição modificada)
 * @summary Duplicar transação
 */
export type postApiV1TransactionsIdDuplicateResponse201 = {
  data: Transaction;
  status: 201;
};

export type postApiV1TransactionsIdDuplicateResponse400 = {
  data: Error;
  status: 400;
};

export type postApiV1TransactionsIdDuplicateResponse401 = {
  data: void;
  status: 401;
};

export type postApiV1TransactionsIdDuplicateResponse403 = {
  data: void;
  status: 403;
};

export type postApiV1TransactionsIdDuplicateResponse404 = {
  data: void;
  status: 404;
};

export type postApiV1TransactionsIdDuplicateResponseSuccess =
  postApiV1TransactionsIdDuplicateResponse201 & {
    headers: Headers;
  };
export type postApiV1TransactionsIdDuplicateResponseError = (
  | postApiV1TransactionsIdDuplicateResponse400
  | postApiV1TransactionsIdDuplicateResponse401
  | postApiV1TransactionsIdDuplicateResponse403
  | postApiV1TransactionsIdDuplicateResponse404
) & {
  headers: Headers;
};

export type postApiV1TransactionsIdDuplicateResponse =
  | postApiV1TransactionsIdDuplicateResponseSuccess
  | postApiV1TransactionsIdDuplicateResponseError;

export const getPostApiV1TransactionsIdDuplicateUrl = (id: string) => {
  return `/api/v1/transactions/${id}/duplicate`;
};

export const postApiV1TransactionsIdDuplicate = async (
  id: string,
  options?: RequestInit
): Promise<postApiV1TransactionsIdDuplicateResponse> => {
  return customInstance<postApiV1TransactionsIdDuplicateResponse>(
    getPostApiV1TransactionsIdDuplicateUrl(id),
    {
      ...options,
      method: 'POST',
    }
  );
};

export const getPostApiV1TransactionsIdDuplicateMutationFetcher = (
  id: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return (_: Key, __: { arg: Arguments }) => {
    return postApiV1TransactionsIdDuplicate(id, options);
  };
};
export const getPostApiV1TransactionsIdDuplicateMutationKey = (id: string) =>
  [`/api/v1/transactions/${id}/duplicate`] as const;

export type PostApiV1TransactionsIdDuplicateMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1TransactionsIdDuplicate>>
>;

/**
 * @summary Duplicar transação
 */
export const usePostApiV1TransactionsIdDuplicate = <TError = Error | void>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof postApiV1TransactionsIdDuplicate>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof postApiV1TransactionsIdDuplicate>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostApiV1TransactionsIdDuplicateMutationKey(id);
  const swrFn = getPostApiV1TransactionsIdDuplicateMutationFetcher(id, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
/**
 * Realiza transferência de valor da conta de origem para conta de destino. Apenas o saldo disponível (available_balance) pode ser transferido.
 * @summary Transferir valor entre contas
 */
export type postApiV1TransactionsTransferResponse201 = {
  data: PostApiV1TransactionsTransfer201;
  status: 201;
};

export type postApiV1TransactionsTransferResponse400 = {
  data: Error;
  status: 400;
};

export type postApiV1TransactionsTransferResponse401 = {
  data: void;
  status: 401;
};

export type postApiV1TransactionsTransferResponse403 = {
  data: void;
  status: 403;
};

export type postApiV1TransactionsTransferResponse404 = {
  data: void;
  status: 404;
};

export type postApiV1TransactionsTransferResponseSuccess =
  postApiV1TransactionsTransferResponse201 & {
    headers: Headers;
  };
export type postApiV1TransactionsTransferResponseError = (
  | postApiV1TransactionsTransferResponse400
  | postApiV1TransactionsTransferResponse401
  | postApiV1TransactionsTransferResponse403
  | postApiV1TransactionsTransferResponse404
) & {
  headers: Headers;
};

export type postApiV1TransactionsTransferResponse =
  | postApiV1TransactionsTransferResponseSuccess
  | postApiV1TransactionsTransferResponseError;

export const getPostApiV1TransactionsTransferUrl = () => {
  return `/api/v1/transactions/transfer`;
};

export const postApiV1TransactionsTransfer = async (
  postApiV1TransactionsTransferBody: PostApiV1TransactionsTransferBody,
  options?: RequestInit
): Promise<postApiV1TransactionsTransferResponse> => {
  return customInstance<postApiV1TransactionsTransferResponse>(
    getPostApiV1TransactionsTransferUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(postApiV1TransactionsTransferBody),
    }
  );
};

export const getPostApiV1TransactionsTransferMutationFetcher = (
  options?: SecondParameter<typeof customInstance>
) => {
  return (_: Key, { arg }: { arg: PostApiV1TransactionsTransferBody }) => {
    return postApiV1TransactionsTransfer(arg, options);
  };
};
export const getPostApiV1TransactionsTransferMutationKey = () =>
  [`/api/v1/transactions/transfer`] as const;

export type PostApiV1TransactionsTransferMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1TransactionsTransfer>>
>;

/**
 * @summary Transferir valor entre contas
 */
export const usePostApiV1TransactionsTransfer = <TError = Error | void>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postApiV1TransactionsTransfer>>,
    TError,
    Key,
    PostApiV1TransactionsTransferBody,
    Awaited<ReturnType<typeof postApiV1TransactionsTransfer>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostApiV1TransactionsTransferMutationKey();
  const swrFn = getPostApiV1TransactionsTransferMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
