/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BFIN API
 * Banking Finance API - Sistema de gestão financeira pessoal
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetApiV1SuggestionsDailyLimit200,
  GetApiV1SuggestionsDailyLimitParams,
} from '../api.schemas';

import { customInstance } from '.././custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getSuggestions = () => {
  /**
   * Retorna o limite diário de gastos calculado para uma conta, incluindo informações sobre gastos do dia e status do limite
   * @summary Obter limite diário de gastos
   */
  const getApiV1SuggestionsDailyLimit = (
    params: GetApiV1SuggestionsDailyLimitParams,
    options?: SecondParameter<typeof customInstance<GetApiV1SuggestionsDailyLimit200>>
  ) => {
    return customInstance<GetApiV1SuggestionsDailyLimit200>(
      { url: `/api/v1/suggestions/daily-limit`, method: 'GET', params },
      options
    );
  };
  return { getApiV1SuggestionsDailyLimit };
};
export type GetApiV1SuggestionsDailyLimitResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSuggestions>['getApiV1SuggestionsDailyLimit']>>
>;
