/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * BFIN API
 * Banking Finance API - Sistema de gestão financeira pessoal
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type { Arguments, Key, SWRConfiguration } from 'swr';

import useSWRMutation from 'swr/mutation';
import type { SWRMutationConfiguration } from 'swr/mutation';

import type {
  GetApiV1LoanSimulations200Item,
  GetApiV1LoanSimulationsParams,
  GetApiV1LoanSimulationsSimulationId200,
  PostApiV1LoanSimulations201,
  PostApiV1LoanSimulationsBody,
  PostApiV1LoanSimulationsIdApprove200,
  PostApiV1LoanSimulationsIdWithdraw200,
} from '../hooks.schemas';

import { customInstance } from '../../client/custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Criar uma simulação de empréstimo com reserva
 */
export type postApiV1LoanSimulationsResponse201 = {
  data: PostApiV1LoanSimulations201;
  status: 201;
};

export type postApiV1LoanSimulationsResponse400 = {
  data: void;
  status: 400;
};

export type postApiV1LoanSimulationsResponse401 = {
  data: void;
  status: 401;
};

export type postApiV1LoanSimulationsResponseSuccess = postApiV1LoanSimulationsResponse201 & {
  headers: Headers;
};
export type postApiV1LoanSimulationsResponseError = (
  | postApiV1LoanSimulationsResponse400
  | postApiV1LoanSimulationsResponse401
) & {
  headers: Headers;
};

export type postApiV1LoanSimulationsResponse =
  | postApiV1LoanSimulationsResponseSuccess
  | postApiV1LoanSimulationsResponseError;

export const getPostApiV1LoanSimulationsUrl = () => {
  return `/api/v1/loan-simulations`;
};

export const postApiV1LoanSimulations = async (
  postApiV1LoanSimulationsBody: PostApiV1LoanSimulationsBody,
  options?: RequestInit
): Promise<postApiV1LoanSimulationsResponse> => {
  return customInstance<postApiV1LoanSimulationsResponse>(getPostApiV1LoanSimulationsUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postApiV1LoanSimulationsBody),
  });
};

export const getPostApiV1LoanSimulationsMutationFetcher = (
  options?: SecondParameter<typeof customInstance>
) => {
  return (_: Key, { arg }: { arg: PostApiV1LoanSimulationsBody }) => {
    return postApiV1LoanSimulations(arg, options);
  };
};
export const getPostApiV1LoanSimulationsMutationKey = () => [`/api/v1/loan-simulations`] as const;

export type PostApiV1LoanSimulationsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1LoanSimulations>>
>;

/**
 * @summary Criar uma simulação de empréstimo com reserva
 */
export const usePostApiV1LoanSimulations = <TError = void>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postApiV1LoanSimulations>>,
    TError,
    Key,
    PostApiV1LoanSimulationsBody,
    Awaited<ReturnType<typeof postApiV1LoanSimulations>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostApiV1LoanSimulationsMutationKey();
  const swrFn = getPostApiV1LoanSimulationsMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
/**
 * Retorna lista paginada de simulações do usuário, opcionalmente filtrada por status
 * @summary Listar simulações com filtro de status
 */
export type getApiV1LoanSimulationsResponse200 = {
  data: GetApiV1LoanSimulations200Item[];
  status: 200;
};

export type getApiV1LoanSimulationsResponse400 = {
  data: void;
  status: 400;
};

export type getApiV1LoanSimulationsResponse401 = {
  data: void;
  status: 401;
};

export type getApiV1LoanSimulationsResponseSuccess = getApiV1LoanSimulationsResponse200 & {
  headers: Headers;
};
export type getApiV1LoanSimulationsResponseError = (
  | getApiV1LoanSimulationsResponse400
  | getApiV1LoanSimulationsResponse401
) & {
  headers: Headers;
};

export type getApiV1LoanSimulationsResponse =
  | getApiV1LoanSimulationsResponseSuccess
  | getApiV1LoanSimulationsResponseError;

export const getGetApiV1LoanSimulationsUrl = (params?: GetApiV1LoanSimulationsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/loan-simulations?${stringifiedParams}`
    : `/api/v1/loan-simulations`;
};

export const getApiV1LoanSimulations = async (
  params?: GetApiV1LoanSimulationsParams,
  options?: RequestInit
): Promise<getApiV1LoanSimulationsResponse> => {
  return customInstance<getApiV1LoanSimulationsResponse>(getGetApiV1LoanSimulationsUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getGetApiV1LoanSimulationsKey = (params?: GetApiV1LoanSimulationsParams) =>
  [`/api/v1/loan-simulations`, ...(params ? [params] : [])] as const;

export type GetApiV1LoanSimulationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1LoanSimulations>>
>;

/**
 * @summary Listar simulações com filtro de status
 */
export const useGetApiV1LoanSimulations = <TError = void>(
  params?: GetApiV1LoanSimulationsParams,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getApiV1LoanSimulations>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetApiV1LoanSimulationsKey(params) : null));
  const swrFn = () => getApiV1LoanSimulations(params, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
/**
 * Retorna todos os detalhes incluindo plano de parcelas e informações de status
 * @summary Obter detalhes completos de uma simulação
 */
export type getApiV1LoanSimulationsSimulationIdResponse200 = {
  data: GetApiV1LoanSimulationsSimulationId200;
  status: 200;
};

export type getApiV1LoanSimulationsSimulationIdResponse401 = {
  data: void;
  status: 401;
};

export type getApiV1LoanSimulationsSimulationIdResponse404 = {
  data: void;
  status: 404;
};

export type getApiV1LoanSimulationsSimulationIdResponseSuccess =
  getApiV1LoanSimulationsSimulationIdResponse200 & {
    headers: Headers;
  };
export type getApiV1LoanSimulationsSimulationIdResponseError = (
  | getApiV1LoanSimulationsSimulationIdResponse401
  | getApiV1LoanSimulationsSimulationIdResponse404
) & {
  headers: Headers;
};

export type getApiV1LoanSimulationsSimulationIdResponse =
  | getApiV1LoanSimulationsSimulationIdResponseSuccess
  | getApiV1LoanSimulationsSimulationIdResponseError;

export const getGetApiV1LoanSimulationsSimulationIdUrl = (simulationId: string) => {
  return `/api/v1/loan-simulations/${simulationId}`;
};

export const getApiV1LoanSimulationsSimulationId = async (
  simulationId: string,
  options?: RequestInit
): Promise<getApiV1LoanSimulationsSimulationIdResponse> => {
  return customInstance<getApiV1LoanSimulationsSimulationIdResponse>(
    getGetApiV1LoanSimulationsSimulationIdUrl(simulationId),
    {
      ...options,
      method: 'GET',
    }
  );
};

export const getGetApiV1LoanSimulationsSimulationIdKey = (simulationId: string) =>
  [`/api/v1/loan-simulations/${simulationId}`] as const;

export type GetApiV1LoanSimulationsSimulationIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1LoanSimulationsSimulationId>>
>;

/**
 * @summary Obter detalhes completos de uma simulação
 */
export const useGetApiV1LoanSimulationsSimulationId = <TError = void>(
  simulationId: string,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof getApiV1LoanSimulationsSimulationId>>,
      TError
    > & { swrKey?: Key; enabled?: boolean };
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && !!simulationId;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getGetApiV1LoanSimulationsSimulationIdKey(simulationId) : null));
  const swrFn = () => getApiV1LoanSimulationsSimulationId(simulationId, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
/**
 * Aprova uma simulação existente, validando status PENDING, expiração de 30 dias e limite de 70% da reserva
 * @summary Aprovar uma simulação de empréstimo
 */
export type postApiV1LoanSimulationsIdApproveResponse200 = {
  data: PostApiV1LoanSimulationsIdApprove200;
  status: 200;
};

export type postApiV1LoanSimulationsIdApproveResponse400 = {
  data: void;
  status: 400;
};

export type postApiV1LoanSimulationsIdApproveResponse401 = {
  data: void;
  status: 401;
};

export type postApiV1LoanSimulationsIdApproveResponse404 = {
  data: void;
  status: 404;
};

export type postApiV1LoanSimulationsIdApproveResponseSuccess =
  postApiV1LoanSimulationsIdApproveResponse200 & {
    headers: Headers;
  };
export type postApiV1LoanSimulationsIdApproveResponseError = (
  | postApiV1LoanSimulationsIdApproveResponse400
  | postApiV1LoanSimulationsIdApproveResponse401
  | postApiV1LoanSimulationsIdApproveResponse404
) & {
  headers: Headers;
};

export type postApiV1LoanSimulationsIdApproveResponse =
  | postApiV1LoanSimulationsIdApproveResponseSuccess
  | postApiV1LoanSimulationsIdApproveResponseError;

export const getPostApiV1LoanSimulationsIdApproveUrl = (id: string) => {
  return `/api/v1/loan-simulations/${id}/approve`;
};

export const postApiV1LoanSimulationsIdApprove = async (
  id: string,
  options?: RequestInit
): Promise<postApiV1LoanSimulationsIdApproveResponse> => {
  return customInstance<postApiV1LoanSimulationsIdApproveResponse>(
    getPostApiV1LoanSimulationsIdApproveUrl(id),
    {
      ...options,
      method: 'POST',
    }
  );
};

export const getPostApiV1LoanSimulationsIdApproveMutationFetcher = (
  id: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return (_: Key, __: { arg: Arguments }) => {
    return postApiV1LoanSimulationsIdApprove(id, options);
  };
};
export const getPostApiV1LoanSimulationsIdApproveMutationKey = (id: string) =>
  [`/api/v1/loan-simulations/${id}/approve`] as const;

export type PostApiV1LoanSimulationsIdApproveMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1LoanSimulationsIdApprove>>
>;

/**
 * @summary Aprovar uma simulação de empréstimo
 */
export const usePostApiV1LoanSimulationsIdApprove = <TError = void>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof postApiV1LoanSimulationsIdApprove>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof postApiV1LoanSimulationsIdApprove>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostApiV1LoanSimulationsIdApproveMutationKey(id);
  const swrFn = getPostApiV1LoanSimulationsIdApproveMutationFetcher(id, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
/**
 * Executa a retirada de fundos da reserva de emergência para o saldo disponível após aprovação da simulação
 * @summary Retirar fundos da reserva de emergência
 */
export type postApiV1LoanSimulationsIdWithdrawResponse200 = {
  data: PostApiV1LoanSimulationsIdWithdraw200;
  status: 200;
};

export type postApiV1LoanSimulationsIdWithdrawResponse400 = {
  data: void;
  status: 400;
};

export type postApiV1LoanSimulationsIdWithdrawResponse401 = {
  data: void;
  status: 401;
};

export type postApiV1LoanSimulationsIdWithdrawResponse404 = {
  data: void;
  status: 404;
};

export type postApiV1LoanSimulationsIdWithdrawResponseSuccess =
  postApiV1LoanSimulationsIdWithdrawResponse200 & {
    headers: Headers;
  };
export type postApiV1LoanSimulationsIdWithdrawResponseError = (
  | postApiV1LoanSimulationsIdWithdrawResponse400
  | postApiV1LoanSimulationsIdWithdrawResponse401
  | postApiV1LoanSimulationsIdWithdrawResponse404
) & {
  headers: Headers;
};

export type postApiV1LoanSimulationsIdWithdrawResponse =
  | postApiV1LoanSimulationsIdWithdrawResponseSuccess
  | postApiV1LoanSimulationsIdWithdrawResponseError;

export const getPostApiV1LoanSimulationsIdWithdrawUrl = (id: string) => {
  return `/api/v1/loan-simulations/${id}/withdraw`;
};

export const postApiV1LoanSimulationsIdWithdraw = async (
  id: string,
  options?: RequestInit
): Promise<postApiV1LoanSimulationsIdWithdrawResponse> => {
  return customInstance<postApiV1LoanSimulationsIdWithdrawResponse>(
    getPostApiV1LoanSimulationsIdWithdrawUrl(id),
    {
      ...options,
      method: 'POST',
    }
  );
};

export const getPostApiV1LoanSimulationsIdWithdrawMutationFetcher = (
  id: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return (_: Key, __: { arg: Arguments }) => {
    return postApiV1LoanSimulationsIdWithdraw(id, options);
  };
};
export const getPostApiV1LoanSimulationsIdWithdrawMutationKey = (id: string) =>
  [`/api/v1/loan-simulations/${id}/withdraw`] as const;

export type PostApiV1LoanSimulationsIdWithdrawMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1LoanSimulationsIdWithdraw>>
>;

/**
 * @summary Retirar fundos da reserva de emergência
 */
export const usePostApiV1LoanSimulationsIdWithdraw = <TError = void>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof postApiV1LoanSimulationsIdWithdraw>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof postApiV1LoanSimulationsIdWithdraw>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostApiV1LoanSimulationsIdWithdrawMutationKey(id);
  const swrFn = getPostApiV1LoanSimulationsIdWithdrawMutationFetcher(id, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
