/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * BFIN API
 * Banking Finance API - Sistema de gestão financeira pessoal
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type { Arguments, Key, SWRConfiguration } from 'swr';

import useSWRMutation from 'swr/mutation';
import type { SWRMutationConfiguration } from 'swr/mutation';

import type {
  GetApiV1LoanSimulations200Item,
  GetApiV1LoanSimulationsParams,
  GetApiV1LoanSimulationsSimulationId200,
  PostApiV1LoanSimulations201,
  PostApiV1LoanSimulationsBody,
  PostApiV1LoanSimulationsIdApprove200,
  PostApiV1LoanSimulationsIdWithdraw200,
} from '../hooks.schemas';

import { customInstance } from '../../client/custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Criar uma simulação de empréstimo com reserva
 */
export const postApiV1LoanSimulations = (
  postApiV1LoanSimulationsBody: PostApiV1LoanSimulationsBody,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<PostApiV1LoanSimulations201>(
    {
      url: `/api/v1/loan-simulations`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: postApiV1LoanSimulationsBody,
    },
    options
  );
};

export const getPostApiV1LoanSimulationsMutationFetcher = (
  options?: SecondParameter<typeof customInstance>
) => {
  return (_: Key, { arg }: { arg: PostApiV1LoanSimulationsBody }) => {
    return postApiV1LoanSimulations(arg, options);
  };
};
export const getPostApiV1LoanSimulationsMutationKey = () => [`/api/v1/loan-simulations`] as const;

export type PostApiV1LoanSimulationsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1LoanSimulations>>
>;
export type PostApiV1LoanSimulationsMutationError = void;

/**
 * @summary Criar uma simulação de empréstimo com reserva
 */
export const usePostApiV1LoanSimulations = <TError = void>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postApiV1LoanSimulations>>,
    TError,
    Key,
    PostApiV1LoanSimulationsBody,
    Awaited<ReturnType<typeof postApiV1LoanSimulations>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostApiV1LoanSimulationsMutationKey();
  const swrFn = getPostApiV1LoanSimulationsMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
/**
 * Retorna lista paginada de simulações do usuário, opcionalmente filtrada por status
 * @summary Listar simulações com filtro de status
 */
export const getApiV1LoanSimulations = (
  params?: GetApiV1LoanSimulationsParams,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<GetApiV1LoanSimulations200Item[]>(
    { url: `/api/v1/loan-simulations`, method: 'GET', params },
    options
  );
};

export const getGetApiV1LoanSimulationsKey = (params?: GetApiV1LoanSimulationsParams) =>
  [`/api/v1/loan-simulations`, ...(params ? [params] : [])] as const;

export type GetApiV1LoanSimulationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1LoanSimulations>>
>;
export type GetApiV1LoanSimulationsQueryError = void;

/**
 * @summary Listar simulações com filtro de status
 */
export const useGetApiV1LoanSimulations = <TError = void>(
  params?: GetApiV1LoanSimulationsParams,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getApiV1LoanSimulations>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetApiV1LoanSimulationsKey(params) : null));
  const swrFn = () => getApiV1LoanSimulations(params, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
/**
 * Retorna todos os detalhes incluindo plano de parcelas e informações de status
 * @summary Obter detalhes completos de uma simulação
 */
export const getApiV1LoanSimulationsSimulationId = (
  simulationId: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<GetApiV1LoanSimulationsSimulationId200>(
    { url: `/api/v1/loan-simulations/${simulationId}`, method: 'GET' },
    options
  );
};

export const getGetApiV1LoanSimulationsSimulationIdKey = (simulationId: string) =>
  [`/api/v1/loan-simulations/${simulationId}`] as const;

export type GetApiV1LoanSimulationsSimulationIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1LoanSimulationsSimulationId>>
>;
export type GetApiV1LoanSimulationsSimulationIdQueryError = void;

/**
 * @summary Obter detalhes completos de uma simulação
 */
export const useGetApiV1LoanSimulationsSimulationId = <TError = void>(
  simulationId: string,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof getApiV1LoanSimulationsSimulationId>>,
      TError
    > & { swrKey?: Key; enabled?: boolean };
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && !!simulationId;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getGetApiV1LoanSimulationsSimulationIdKey(simulationId) : null));
  const swrFn = () => getApiV1LoanSimulationsSimulationId(simulationId, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
/**
 * Aprova uma simulação existente, validando status PENDING, expiração de 30 dias e limite de 70% da reserva
 * @summary Aprovar uma simulação de empréstimo
 */
export const postApiV1LoanSimulationsIdApprove = (
  id: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<PostApiV1LoanSimulationsIdApprove200>(
    { url: `/api/v1/loan-simulations/${id}/approve`, method: 'POST' },
    options
  );
};

export const getPostApiV1LoanSimulationsIdApproveMutationFetcher = (
  id: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return (_: Key, __: { arg: Arguments }) => {
    return postApiV1LoanSimulationsIdApprove(id, options);
  };
};
export const getPostApiV1LoanSimulationsIdApproveMutationKey = (id: string) =>
  [`/api/v1/loan-simulations/${id}/approve`] as const;

export type PostApiV1LoanSimulationsIdApproveMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1LoanSimulationsIdApprove>>
>;
export type PostApiV1LoanSimulationsIdApproveMutationError = void;

/**
 * @summary Aprovar uma simulação de empréstimo
 */
export const usePostApiV1LoanSimulationsIdApprove = <TError = void>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof postApiV1LoanSimulationsIdApprove>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof postApiV1LoanSimulationsIdApprove>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostApiV1LoanSimulationsIdApproveMutationKey(id);
  const swrFn = getPostApiV1LoanSimulationsIdApproveMutationFetcher(id, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
/**
 * Executa a retirada de fundos da reserva de emergência para o saldo disponível após aprovação da simulação
 * @summary Retirar fundos da reserva de emergência
 */
export const postApiV1LoanSimulationsIdWithdraw = (
  id: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<PostApiV1LoanSimulationsIdWithdraw200>(
    { url: `/api/v1/loan-simulations/${id}/withdraw`, method: 'POST' },
    options
  );
};

export const getPostApiV1LoanSimulationsIdWithdrawMutationFetcher = (
  id: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return (_: Key, __: { arg: Arguments }) => {
    return postApiV1LoanSimulationsIdWithdraw(id, options);
  };
};
export const getPostApiV1LoanSimulationsIdWithdrawMutationKey = (id: string) =>
  [`/api/v1/loan-simulations/${id}/withdraw`] as const;

export type PostApiV1LoanSimulationsIdWithdrawMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1LoanSimulationsIdWithdraw>>
>;
export type PostApiV1LoanSimulationsIdWithdrawMutationError = void;

/**
 * @summary Retirar fundos da reserva de emergência
 */
export const usePostApiV1LoanSimulationsIdWithdraw = <TError = void>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof postApiV1LoanSimulationsIdWithdraw>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof postApiV1LoanSimulationsIdWithdraw>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostApiV1LoanSimulationsIdWithdrawMutationKey(id);
  const swrFn = getPostApiV1LoanSimulationsIdWithdrawMutationFetcher(id, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
