/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * BFIN API
 * Banking Finance API - Sistema de gestão financeira pessoal
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  GetApiV1LoanSimulations200Item,
  GetApiV1LoanSimulationsParams,
  GetApiV1LoanSimulationsSimulationId200,
  PostApiV1LoanSimulations201,
  PostApiV1LoanSimulationsBody,
  PostApiV1LoanSimulationsIdApprove200,
  PostApiV1LoanSimulationsIdWithdraw200,
} from '../hooks.schemas';

import { customInstance } from '../../client/custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Criar uma simulação de empréstimo com reserva
 */
export type postApiV1LoanSimulationsResponse201 = {
  data: PostApiV1LoanSimulations201;
  status: 201;
};

export type postApiV1LoanSimulationsResponse400 = {
  data: void;
  status: 400;
};

export type postApiV1LoanSimulationsResponse401 = {
  data: void;
  status: 401;
};

export type postApiV1LoanSimulationsResponseSuccess = postApiV1LoanSimulationsResponse201 & {
  headers: Headers;
};
export type postApiV1LoanSimulationsResponseError = (
  | postApiV1LoanSimulationsResponse400
  | postApiV1LoanSimulationsResponse401
) & {
  headers: Headers;
};

export type postApiV1LoanSimulationsResponse =
  | postApiV1LoanSimulationsResponseSuccess
  | postApiV1LoanSimulationsResponseError;

export const getPostApiV1LoanSimulationsUrl = () => {
  return `/api/v1/loan-simulations`;
};

export const postApiV1LoanSimulations = async (
  postApiV1LoanSimulationsBody: PostApiV1LoanSimulationsBody,
  options?: RequestInit
): Promise<postApiV1LoanSimulationsResponse> => {
  return customInstance<postApiV1LoanSimulationsResponse>(getPostApiV1LoanSimulationsUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postApiV1LoanSimulationsBody),
  });
};

export const getPostApiV1LoanSimulationsMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1LoanSimulations>>,
    TError,
    { data: PostApiV1LoanSimulationsBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiV1LoanSimulations>>,
  TError,
  { data: PostApiV1LoanSimulationsBody },
  TContext
> => {
  const mutationKey = ['postApiV1LoanSimulations'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiV1LoanSimulations>>,
    { data: PostApiV1LoanSimulationsBody }
  > = (props) => {
    const { data } = props ?? {};

    return postApiV1LoanSimulations(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiV1LoanSimulationsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1LoanSimulations>>
>;
export type PostApiV1LoanSimulationsMutationBody = PostApiV1LoanSimulationsBody;
export type PostApiV1LoanSimulationsMutationError = void;

/**
 * @summary Criar uma simulação de empréstimo com reserva
 */
export const usePostApiV1LoanSimulations = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1LoanSimulations>>,
    TError,
    { data: PostApiV1LoanSimulationsBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof postApiV1LoanSimulations>>,
  TError,
  { data: PostApiV1LoanSimulationsBody },
  TContext
> => {
  return useMutation(getPostApiV1LoanSimulationsMutationOptions(options));
};
/**
 * Retorna lista paginada de simulações do usuário, opcionalmente filtrada por status
 * @summary Listar simulações com filtro de status
 */
export type getApiV1LoanSimulationsResponse200 = {
  data: GetApiV1LoanSimulations200Item[];
  status: 200;
};

export type getApiV1LoanSimulationsResponse400 = {
  data: void;
  status: 400;
};

export type getApiV1LoanSimulationsResponse401 = {
  data: void;
  status: 401;
};

export type getApiV1LoanSimulationsResponseSuccess = getApiV1LoanSimulationsResponse200 & {
  headers: Headers;
};
export type getApiV1LoanSimulationsResponseError = (
  | getApiV1LoanSimulationsResponse400
  | getApiV1LoanSimulationsResponse401
) & {
  headers: Headers;
};

export type getApiV1LoanSimulationsResponse =
  | getApiV1LoanSimulationsResponseSuccess
  | getApiV1LoanSimulationsResponseError;

export const getGetApiV1LoanSimulationsUrl = (params?: GetApiV1LoanSimulationsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/loan-simulations?${stringifiedParams}`
    : `/api/v1/loan-simulations`;
};

export const getApiV1LoanSimulations = async (
  params?: GetApiV1LoanSimulationsParams,
  options?: RequestInit
): Promise<getApiV1LoanSimulationsResponse> => {
  return customInstance<getApiV1LoanSimulationsResponse>(getGetApiV1LoanSimulationsUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getGetApiV1LoanSimulationsQueryKey = (params?: GetApiV1LoanSimulationsParams) => {
  return [`/api/v1/loan-simulations`, ...(params ? [params] : [])] as const;
};

export const getGetApiV1LoanSimulationsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1LoanSimulations>>,
  TError = void,
>(
  params?: GetApiV1LoanSimulationsParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getApiV1LoanSimulations>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiV1LoanSimulationsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1LoanSimulations>>> = ({
    signal,
  }) => getApiV1LoanSimulations(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1LoanSimulations>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetApiV1LoanSimulationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1LoanSimulations>>
>;
export type GetApiV1LoanSimulationsQueryError = void;

/**
 * @summary Listar simulações com filtro de status
 */

export function useGetApiV1LoanSimulations<
  TData = Awaited<ReturnType<typeof getApiV1LoanSimulations>>,
  TError = void,
>(
  params?: GetApiV1LoanSimulationsParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getApiV1LoanSimulations>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetApiV1LoanSimulationsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Retorna todos os detalhes incluindo plano de parcelas e informações de status
 * @summary Obter detalhes completos de uma simulação
 */
export type getApiV1LoanSimulationsSimulationIdResponse200 = {
  data: GetApiV1LoanSimulationsSimulationId200;
  status: 200;
};

export type getApiV1LoanSimulationsSimulationIdResponse401 = {
  data: void;
  status: 401;
};

export type getApiV1LoanSimulationsSimulationIdResponse404 = {
  data: void;
  status: 404;
};

export type getApiV1LoanSimulationsSimulationIdResponseSuccess =
  getApiV1LoanSimulationsSimulationIdResponse200 & {
    headers: Headers;
  };
export type getApiV1LoanSimulationsSimulationIdResponseError = (
  | getApiV1LoanSimulationsSimulationIdResponse401
  | getApiV1LoanSimulationsSimulationIdResponse404
) & {
  headers: Headers;
};

export type getApiV1LoanSimulationsSimulationIdResponse =
  | getApiV1LoanSimulationsSimulationIdResponseSuccess
  | getApiV1LoanSimulationsSimulationIdResponseError;

export const getGetApiV1LoanSimulationsSimulationIdUrl = (simulationId: string) => {
  return `/api/v1/loan-simulations/${simulationId}`;
};

export const getApiV1LoanSimulationsSimulationId = async (
  simulationId: string,
  options?: RequestInit
): Promise<getApiV1LoanSimulationsSimulationIdResponse> => {
  return customInstance<getApiV1LoanSimulationsSimulationIdResponse>(
    getGetApiV1LoanSimulationsSimulationIdUrl(simulationId),
    {
      ...options,
      method: 'GET',
    }
  );
};

export const getGetApiV1LoanSimulationsSimulationIdQueryKey = (simulationId: string) => {
  return [`/api/v1/loan-simulations/${simulationId}`] as const;
};

export const getGetApiV1LoanSimulationsSimulationIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1LoanSimulationsSimulationId>>,
  TError = void,
>(
  simulationId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getApiV1LoanSimulationsSimulationId>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiV1LoanSimulationsSimulationIdQueryKey(simulationId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1LoanSimulationsSimulationId>>> = ({
    signal,
  }) => getApiV1LoanSimulationsSimulationId(simulationId, { signal, ...requestOptions });

  return { queryKey, queryFn, enabled: !!simulationId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1LoanSimulationsSimulationId>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetApiV1LoanSimulationsSimulationIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1LoanSimulationsSimulationId>>
>;
export type GetApiV1LoanSimulationsSimulationIdQueryError = void;

/**
 * @summary Obter detalhes completos de uma simulação
 */

export function useGetApiV1LoanSimulationsSimulationId<
  TData = Awaited<ReturnType<typeof getApiV1LoanSimulationsSimulationId>>,
  TError = void,
>(
  simulationId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getApiV1LoanSimulationsSimulationId>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetApiV1LoanSimulationsSimulationIdQueryOptions(simulationId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Aprova uma simulação existente, validando status PENDING, expiração de 30 dias e limite de 70% da reserva
 * @summary Aprovar uma simulação de empréstimo
 */
export type postApiV1LoanSimulationsIdApproveResponse200 = {
  data: PostApiV1LoanSimulationsIdApprove200;
  status: 200;
};

export type postApiV1LoanSimulationsIdApproveResponse400 = {
  data: void;
  status: 400;
};

export type postApiV1LoanSimulationsIdApproveResponse401 = {
  data: void;
  status: 401;
};

export type postApiV1LoanSimulationsIdApproveResponse404 = {
  data: void;
  status: 404;
};

export type postApiV1LoanSimulationsIdApproveResponseSuccess =
  postApiV1LoanSimulationsIdApproveResponse200 & {
    headers: Headers;
  };
export type postApiV1LoanSimulationsIdApproveResponseError = (
  | postApiV1LoanSimulationsIdApproveResponse400
  | postApiV1LoanSimulationsIdApproveResponse401
  | postApiV1LoanSimulationsIdApproveResponse404
) & {
  headers: Headers;
};

export type postApiV1LoanSimulationsIdApproveResponse =
  | postApiV1LoanSimulationsIdApproveResponseSuccess
  | postApiV1LoanSimulationsIdApproveResponseError;

export const getPostApiV1LoanSimulationsIdApproveUrl = (id: string) => {
  return `/api/v1/loan-simulations/${id}/approve`;
};

export const postApiV1LoanSimulationsIdApprove = async (
  id: string,
  options?: RequestInit
): Promise<postApiV1LoanSimulationsIdApproveResponse> => {
  return customInstance<postApiV1LoanSimulationsIdApproveResponse>(
    getPostApiV1LoanSimulationsIdApproveUrl(id),
    {
      ...options,
      method: 'POST',
    }
  );
};

export const getPostApiV1LoanSimulationsIdApproveMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1LoanSimulationsIdApprove>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiV1LoanSimulationsIdApprove>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['postApiV1LoanSimulationsIdApprove'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiV1LoanSimulationsIdApprove>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return postApiV1LoanSimulationsIdApprove(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiV1LoanSimulationsIdApproveMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1LoanSimulationsIdApprove>>
>;

export type PostApiV1LoanSimulationsIdApproveMutationError = void;

/**
 * @summary Aprovar uma simulação de empréstimo
 */
export const usePostApiV1LoanSimulationsIdApprove = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1LoanSimulationsIdApprove>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof postApiV1LoanSimulationsIdApprove>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getPostApiV1LoanSimulationsIdApproveMutationOptions(options));
};
/**
 * Executa a retirada de fundos da reserva de emergência para o saldo disponível após aprovação da simulação
 * @summary Retirar fundos da reserva de emergência
 */
export type postApiV1LoanSimulationsIdWithdrawResponse200 = {
  data: PostApiV1LoanSimulationsIdWithdraw200;
  status: 200;
};

export type postApiV1LoanSimulationsIdWithdrawResponse400 = {
  data: void;
  status: 400;
};

export type postApiV1LoanSimulationsIdWithdrawResponse401 = {
  data: void;
  status: 401;
};

export type postApiV1LoanSimulationsIdWithdrawResponse404 = {
  data: void;
  status: 404;
};

export type postApiV1LoanSimulationsIdWithdrawResponseSuccess =
  postApiV1LoanSimulationsIdWithdrawResponse200 & {
    headers: Headers;
  };
export type postApiV1LoanSimulationsIdWithdrawResponseError = (
  | postApiV1LoanSimulationsIdWithdrawResponse400
  | postApiV1LoanSimulationsIdWithdrawResponse401
  | postApiV1LoanSimulationsIdWithdrawResponse404
) & {
  headers: Headers;
};

export type postApiV1LoanSimulationsIdWithdrawResponse =
  | postApiV1LoanSimulationsIdWithdrawResponseSuccess
  | postApiV1LoanSimulationsIdWithdrawResponseError;

export const getPostApiV1LoanSimulationsIdWithdrawUrl = (id: string) => {
  return `/api/v1/loan-simulations/${id}/withdraw`;
};

export const postApiV1LoanSimulationsIdWithdraw = async (
  id: string,
  options?: RequestInit
): Promise<postApiV1LoanSimulationsIdWithdrawResponse> => {
  return customInstance<postApiV1LoanSimulationsIdWithdrawResponse>(
    getPostApiV1LoanSimulationsIdWithdrawUrl(id),
    {
      ...options,
      method: 'POST',
    }
  );
};

export const getPostApiV1LoanSimulationsIdWithdrawMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1LoanSimulationsIdWithdraw>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiV1LoanSimulationsIdWithdraw>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['postApiV1LoanSimulationsIdWithdraw'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiV1LoanSimulationsIdWithdraw>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return postApiV1LoanSimulationsIdWithdraw(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiV1LoanSimulationsIdWithdrawMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1LoanSimulationsIdWithdraw>>
>;

export type PostApiV1LoanSimulationsIdWithdrawMutationError = void;

/**
 * @summary Retirar fundos da reserva de emergência
 */
export const usePostApiV1LoanSimulationsIdWithdraw = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1LoanSimulationsIdWithdraw>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof postApiV1LoanSimulationsIdWithdraw>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getPostApiV1LoanSimulationsIdWithdrawMutationOptions(options));
};
