/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BFIN API
 * Banking Finance API - Sistema de gestão financeira pessoal
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  GetApiV1LoanSimulations200Item,
  GetApiV1LoanSimulationsParams,
  PostApiV1LoanSimulations201,
  PostApiV1LoanSimulationsBody,
} from '../hooks.schemas';

import { customInstance } from '../../client/custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Criar uma simulação de empréstimo com reserva
 */
export const postApiV1LoanSimulations = (
  postApiV1LoanSimulationsBody: PostApiV1LoanSimulationsBody,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<PostApiV1LoanSimulations201>(
    {
      url: `/api/v1/loan-simulations`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: postApiV1LoanSimulationsBody,
      signal,
    },
    options
  );
};

export const getPostApiV1LoanSimulationsMutationOptions = <
  TError = void | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1LoanSimulations>>,
    TError,
    { data: PostApiV1LoanSimulationsBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiV1LoanSimulations>>,
  TError,
  { data: PostApiV1LoanSimulationsBody },
  TContext
> => {
  const mutationKey = ['postApiV1LoanSimulations'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiV1LoanSimulations>>,
    { data: PostApiV1LoanSimulationsBody }
  > = (props) => {
    const { data } = props ?? {};

    return postApiV1LoanSimulations(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiV1LoanSimulationsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1LoanSimulations>>
>;
export type PostApiV1LoanSimulationsMutationBody = PostApiV1LoanSimulationsBody;
export type PostApiV1LoanSimulationsMutationError = void | void;

/**
 * @summary Criar uma simulação de empréstimo com reserva
 */
export const usePostApiV1LoanSimulations = <TError = void | void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1LoanSimulations>>,
    TError,
    { data: PostApiV1LoanSimulationsBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof postApiV1LoanSimulations>>,
  TError,
  { data: PostApiV1LoanSimulationsBody },
  TContext
> => {
  const mutationOptions = getPostApiV1LoanSimulationsMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Listar simulações
 */
export const getApiV1LoanSimulations = (
  params?: GetApiV1LoanSimulationsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<GetApiV1LoanSimulations200Item[]>(
    { url: `/api/v1/loan-simulations`, method: 'GET', params, signal },
    options
  );
};

export const getGetApiV1LoanSimulationsQueryKey = (params?: GetApiV1LoanSimulationsParams) => {
  return [`/api/v1/loan-simulations`, ...(params ? [params] : [])] as const;
};

export const getGetApiV1LoanSimulationsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1LoanSimulations>>,
  TError = void,
>(
  params?: GetApiV1LoanSimulationsParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getApiV1LoanSimulations>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiV1LoanSimulationsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1LoanSimulations>>> = ({
    signal,
  }) => getApiV1LoanSimulations(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1LoanSimulations>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetApiV1LoanSimulationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1LoanSimulations>>
>;
export type GetApiV1LoanSimulationsQueryError = void;

/**
 * @summary Listar simulações
 */

export function useGetApiV1LoanSimulations<
  TData = Awaited<ReturnType<typeof getApiV1LoanSimulations>>,
  TError = void,
>(
  params?: GetApiV1LoanSimulationsParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getApiV1LoanSimulations>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetApiV1LoanSimulationsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Obter detalhes de uma simulação
 */
export const getApiV1LoanSimulationsSimulationId = (
  simulationId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    { url: `/api/v1/loan-simulations/${simulationId}`, method: 'GET', signal },
    options
  );
};

export const getGetApiV1LoanSimulationsSimulationIdQueryKey = (simulationId?: string) => {
  return [`/api/v1/loan-simulations/${simulationId}`] as const;
};

export const getGetApiV1LoanSimulationsSimulationIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1LoanSimulationsSimulationId>>,
  TError = void | void,
>(
  simulationId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getApiV1LoanSimulationsSimulationId>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiV1LoanSimulationsSimulationIdQueryKey(simulationId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1LoanSimulationsSimulationId>>> = ({
    signal,
  }) => getApiV1LoanSimulationsSimulationId(simulationId, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!simulationId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1LoanSimulationsSimulationId>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetApiV1LoanSimulationsSimulationIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1LoanSimulationsSimulationId>>
>;
export type GetApiV1LoanSimulationsSimulationIdQueryError = void | void;

/**
 * @summary Obter detalhes de uma simulação
 */

export function useGetApiV1LoanSimulationsSimulationId<
  TData = Awaited<ReturnType<typeof getApiV1LoanSimulationsSimulationId>>,
  TError = void | void,
>(
  simulationId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getApiV1LoanSimulationsSimulationId>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetApiV1LoanSimulationsSimulationIdQueryOptions(simulationId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}
