/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BFIN API
 * Banking Finance API - Sistema de gestão financeira pessoal
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type { Arguments, Key, SWRConfiguration } from 'swr';

import useSWRMutation from 'swr/mutation';
import type { SWRMutationConfiguration } from 'swr/mutation';

import type {
  Error,
  GetApiV1InvitationsMyInvitations200Item,
  PostApiV1InvitationsTokenAccept200,
  PostApiV1InvitationsTokenReject200,
} from '../hooks.schemas';

import { customInstance } from '../../client/custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Retorna todos os convites pendentes recebidos pelo usuário logado (não expirados)
 * @summary Listar convites recebidos
 */
export const getApiV1InvitationsMyInvitations = (
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<GetApiV1InvitationsMyInvitations200Item[]>(
    { url: `/api/v1/invitations/my-invitations`, method: 'GET' },
    options
  );
};

export const getGetApiV1InvitationsMyInvitationsKey = () =>
  [`/api/v1/invitations/my-invitations`] as const;

export type GetApiV1InvitationsMyInvitationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1InvitationsMyInvitations>>
>;
export type GetApiV1InvitationsMyInvitationsQueryError = void;

/**
 * @summary Listar convites recebidos
 */
export const useGetApiV1InvitationsMyInvitations = <TError = void>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof getApiV1InvitationsMyInvitations>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetApiV1InvitationsMyInvitationsKey() : null));
  const swrFn = () => getApiV1InvitationsMyInvitations(requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
/**
 * Aceita um convite para participar de uma conta compartilhada. O usuário deve ser o destinatário do convite e o convite deve estar pendente e não expirado.
 * @summary Aceitar convite
 */
export const postApiV1InvitationsTokenAccept = (
  token: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<PostApiV1InvitationsTokenAccept200>(
    { url: `/api/v1/invitations/${token}/accept`, method: 'POST' },
    options
  );
};

export const getPostApiV1InvitationsTokenAcceptMutationFetcher = (
  token: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return (_: Key, __: { arg: Arguments }) => {
    return postApiV1InvitationsTokenAccept(token, options);
  };
};
export const getPostApiV1InvitationsTokenAcceptMutationKey = (token: string) =>
  [`/api/v1/invitations/${token}/accept`] as const;

export type PostApiV1InvitationsTokenAcceptMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1InvitationsTokenAccept>>
>;
export type PostApiV1InvitationsTokenAcceptMutationError = Error | void | Error | Error;

/**
 * @summary Aceitar convite
 */
export const usePostApiV1InvitationsTokenAccept = <TError = Error | void | Error | Error>(
  token: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof postApiV1InvitationsTokenAccept>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof postApiV1InvitationsTokenAccept>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostApiV1InvitationsTokenAcceptMutationKey(token);
  const swrFn = getPostApiV1InvitationsTokenAcceptMutationFetcher(token, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
/**
 * Rejeita um convite para participar de uma conta compartilhada. O usuário deve ser o destinatário do convite e o convite deve estar pendente e não expirado.
 * @summary Rejeitar convite
 */
export const postApiV1InvitationsTokenReject = (
  token: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<PostApiV1InvitationsTokenReject200>(
    { url: `/api/v1/invitations/${token}/reject`, method: 'POST' },
    options
  );
};

export const getPostApiV1InvitationsTokenRejectMutationFetcher = (
  token: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return (_: Key, __: { arg: Arguments }) => {
    return postApiV1InvitationsTokenReject(token, options);
  };
};
export const getPostApiV1InvitationsTokenRejectMutationKey = (token: string) =>
  [`/api/v1/invitations/${token}/reject`] as const;

export type PostApiV1InvitationsTokenRejectMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1InvitationsTokenReject>>
>;
export type PostApiV1InvitationsTokenRejectMutationError = Error | void | Error | Error;

/**
 * @summary Rejeitar convite
 */
export const usePostApiV1InvitationsTokenReject = <TError = Error | void | Error | Error>(
  token: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof postApiV1InvitationsTokenReject>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof postApiV1InvitationsTokenReject>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostApiV1InvitationsTokenRejectMutationKey(token);
  const swrFn = getPostApiV1InvitationsTokenRejectMutationFetcher(token, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
