/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * BFIN API
 * Banking Finance API - Sistema de gestão financeira pessoal
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type { Arguments, Key, SWRConfiguration } from 'swr';

import useSWRMutation from 'swr/mutation';
import type { SWRMutationConfiguration } from 'swr/mutation';

import type {
  Error,
  GetApiV1InvitationsMyInvitations200Item,
  PostApiV1InvitationsTokenAccept200,
  PostApiV1InvitationsTokenReject200,
} from '../hooks.schemas';

import { customInstance } from '../../client/custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Retorna todos os convites pendentes recebidos pelo usuário logado (não expirados)
 * @summary Listar convites recebidos
 */
export type getApiV1InvitationsMyInvitationsResponse200 = {
  data: GetApiV1InvitationsMyInvitations200Item[];
  status: 200;
};

export type getApiV1InvitationsMyInvitationsResponse401 = {
  data: void;
  status: 401;
};

export type getApiV1InvitationsMyInvitationsResponseSuccess =
  getApiV1InvitationsMyInvitationsResponse200 & {
    headers: Headers;
  };
export type getApiV1InvitationsMyInvitationsResponseError =
  getApiV1InvitationsMyInvitationsResponse401 & {
    headers: Headers;
  };

export type getApiV1InvitationsMyInvitationsResponse =
  | getApiV1InvitationsMyInvitationsResponseSuccess
  | getApiV1InvitationsMyInvitationsResponseError;

export const getGetApiV1InvitationsMyInvitationsUrl = () => {
  return `/api/v1/invitations/my-invitations`;
};

export const getApiV1InvitationsMyInvitations = async (
  options?: RequestInit
): Promise<getApiV1InvitationsMyInvitationsResponse> => {
  return customInstance<getApiV1InvitationsMyInvitationsResponse>(
    getGetApiV1InvitationsMyInvitationsUrl(),
    {
      ...options,
      method: 'GET',
    }
  );
};

export const getGetApiV1InvitationsMyInvitationsKey = () =>
  [`/api/v1/invitations/my-invitations`] as const;

export type GetApiV1InvitationsMyInvitationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1InvitationsMyInvitations>>
>;

/**
 * @summary Listar convites recebidos
 */
export const useGetApiV1InvitationsMyInvitations = <TError = void>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof getApiV1InvitationsMyInvitations>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetApiV1InvitationsMyInvitationsKey() : null));
  const swrFn = () => getApiV1InvitationsMyInvitations(requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
/**
 * Aceita um convite para participar de uma conta compartilhada. O usuário deve ser o destinatário do convite e o convite deve estar pendente e não expirado.
 * @summary Aceitar convite
 */
export type postApiV1InvitationsTokenAcceptResponse200 = {
  data: PostApiV1InvitationsTokenAccept200;
  status: 200;
};

export type postApiV1InvitationsTokenAcceptResponse400 = {
  data: Error;
  status: 400;
};

export type postApiV1InvitationsTokenAcceptResponse401 = {
  data: void;
  status: 401;
};

export type postApiV1InvitationsTokenAcceptResponse403 = {
  data: Error;
  status: 403;
};

export type postApiV1InvitationsTokenAcceptResponse404 = {
  data: Error;
  status: 404;
};

export type postApiV1InvitationsTokenAcceptResponseSuccess =
  postApiV1InvitationsTokenAcceptResponse200 & {
    headers: Headers;
  };
export type postApiV1InvitationsTokenAcceptResponseError = (
  | postApiV1InvitationsTokenAcceptResponse400
  | postApiV1InvitationsTokenAcceptResponse401
  | postApiV1InvitationsTokenAcceptResponse403
  | postApiV1InvitationsTokenAcceptResponse404
) & {
  headers: Headers;
};

export type postApiV1InvitationsTokenAcceptResponse =
  | postApiV1InvitationsTokenAcceptResponseSuccess
  | postApiV1InvitationsTokenAcceptResponseError;

export const getPostApiV1InvitationsTokenAcceptUrl = (token: string) => {
  return `/api/v1/invitations/${token}/accept`;
};

export const postApiV1InvitationsTokenAccept = async (
  token: string,
  options?: RequestInit
): Promise<postApiV1InvitationsTokenAcceptResponse> => {
  return customInstance<postApiV1InvitationsTokenAcceptResponse>(
    getPostApiV1InvitationsTokenAcceptUrl(token),
    {
      ...options,
      method: 'POST',
    }
  );
};

export const getPostApiV1InvitationsTokenAcceptMutationFetcher = (
  token: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return (_: Key, __: { arg: Arguments }) => {
    return postApiV1InvitationsTokenAccept(token, options);
  };
};
export const getPostApiV1InvitationsTokenAcceptMutationKey = (token: string) =>
  [`/api/v1/invitations/${token}/accept`] as const;

export type PostApiV1InvitationsTokenAcceptMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1InvitationsTokenAccept>>
>;

/**
 * @summary Aceitar convite
 */
export const usePostApiV1InvitationsTokenAccept = <TError = Error | void>(
  token: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof postApiV1InvitationsTokenAccept>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof postApiV1InvitationsTokenAccept>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostApiV1InvitationsTokenAcceptMutationKey(token);
  const swrFn = getPostApiV1InvitationsTokenAcceptMutationFetcher(token, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
/**
 * Rejeita um convite para participar de uma conta compartilhada. O usuário deve ser o destinatário do convite e o convite deve estar pendente e não expirado.
 * @summary Rejeitar convite
 */
export type postApiV1InvitationsTokenRejectResponse200 = {
  data: PostApiV1InvitationsTokenReject200;
  status: 200;
};

export type postApiV1InvitationsTokenRejectResponse400 = {
  data: Error;
  status: 400;
};

export type postApiV1InvitationsTokenRejectResponse401 = {
  data: void;
  status: 401;
};

export type postApiV1InvitationsTokenRejectResponse403 = {
  data: Error;
  status: 403;
};

export type postApiV1InvitationsTokenRejectResponse404 = {
  data: Error;
  status: 404;
};

export type postApiV1InvitationsTokenRejectResponseSuccess =
  postApiV1InvitationsTokenRejectResponse200 & {
    headers: Headers;
  };
export type postApiV1InvitationsTokenRejectResponseError = (
  | postApiV1InvitationsTokenRejectResponse400
  | postApiV1InvitationsTokenRejectResponse401
  | postApiV1InvitationsTokenRejectResponse403
  | postApiV1InvitationsTokenRejectResponse404
) & {
  headers: Headers;
};

export type postApiV1InvitationsTokenRejectResponse =
  | postApiV1InvitationsTokenRejectResponseSuccess
  | postApiV1InvitationsTokenRejectResponseError;

export const getPostApiV1InvitationsTokenRejectUrl = (token: string) => {
  return `/api/v1/invitations/${token}/reject`;
};

export const postApiV1InvitationsTokenReject = async (
  token: string,
  options?: RequestInit
): Promise<postApiV1InvitationsTokenRejectResponse> => {
  return customInstance<postApiV1InvitationsTokenRejectResponse>(
    getPostApiV1InvitationsTokenRejectUrl(token),
    {
      ...options,
      method: 'POST',
    }
  );
};

export const getPostApiV1InvitationsTokenRejectMutationFetcher = (
  token: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return (_: Key, __: { arg: Arguments }) => {
    return postApiV1InvitationsTokenReject(token, options);
  };
};
export const getPostApiV1InvitationsTokenRejectMutationKey = (token: string) =>
  [`/api/v1/invitations/${token}/reject`] as const;

export type PostApiV1InvitationsTokenRejectMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1InvitationsTokenReject>>
>;

/**
 * @summary Rejeitar convite
 */
export const usePostApiV1InvitationsTokenReject = <TError = Error | void>(
  token: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof postApiV1InvitationsTokenReject>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof postApiV1InvitationsTokenReject>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostApiV1InvitationsTokenRejectMutationKey(token);
  const swrFn = getPostApiV1InvitationsTokenRejectMutationFetcher(token, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
