/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BFIN API
 * Banking Finance API - Sistema de gestão financeira pessoal
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetApiV1InvitationsMyInvitations200Item,
  PostApiV1InvitationsTokenAccept200,
  PostApiV1InvitationsTokenReject200,
} from '../api.schemas';

import { customInstance } from '.././custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getInvitations = () => {
  /**
   * Retorna todos os convites pendentes recebidos pelo usuário logado (não expirados)
   * @summary Listar convites recebidos
   */
  const getApiV1InvitationsMyInvitations = (
    options?: SecondParameter<typeof customInstance<GetApiV1InvitationsMyInvitations200Item[]>>
  ) => {
    return customInstance<GetApiV1InvitationsMyInvitations200Item[]>(
      { url: `/api/v1/invitations/my-invitations`, method: 'GET' },
      options
    );
  };
  /**
   * Aceita um convite para participar de uma conta compartilhada. O usuário deve ser o destinatário do convite e o convite deve estar pendente e não expirado.
   * @summary Aceitar convite
   */
  const postApiV1InvitationsTokenAccept = (
    token: string,
    options?: SecondParameter<typeof customInstance<PostApiV1InvitationsTokenAccept200>>
  ) => {
    return customInstance<PostApiV1InvitationsTokenAccept200>(
      { url: `/api/v1/invitations/${token}/accept`, method: 'POST' },
      options
    );
  };
  /**
   * Rejeita um convite para participar de uma conta compartilhada. O usuário deve ser o destinatário do convite e o convite deve estar pendente e não expirado.
   * @summary Rejeitar convite
   */
  const postApiV1InvitationsTokenReject = (
    token: string,
    options?: SecondParameter<typeof customInstance<PostApiV1InvitationsTokenReject200>>
  ) => {
    return customInstance<PostApiV1InvitationsTokenReject200>(
      { url: `/api/v1/invitations/${token}/reject`, method: 'POST' },
      options
    );
  };
  return {
    getApiV1InvitationsMyInvitations,
    postApiV1InvitationsTokenAccept,
    postApiV1InvitationsTokenReject,
  };
};
export type GetApiV1InvitationsMyInvitationsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getInvitations>['getApiV1InvitationsMyInvitations']>>
>;
export type PostApiV1InvitationsTokenAcceptResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getInvitations>['postApiV1InvitationsTokenAccept']>>
>;
export type PostApiV1InvitationsTokenRejectResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getInvitations>['postApiV1InvitationsTokenReject']>>
>;
