/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BFIN API
 * Banking Finance API - Sistema de gestão financeira pessoal
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  DeleteApiV1TransactionsId200,
  Error,
  GetApiV1Transactions200,
  GetApiV1TransactionsParams,
  PostApiV1TransactionsFixedExpenseBody,
  PostApiV1TransactionsIdMarkAsPaid200,
  PostApiV1TransactionsIncomeBody,
  PostApiV1TransactionsVariableExpenseBody,
  PutApiV1TransactionsId200,
  PutApiV1TransactionsIdBody,
  Transaction,
} from '../hooks.schemas';

import { customInstance } from '../../client/custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Processa uma receita aplicando regras automáticas (30/70 - reserva de emergência e saldo disponível)
 * @summary Criar receita
 */
export const postApiV1TransactionsIncome = (
  postApiV1TransactionsIncomeBody: PostApiV1TransactionsIncomeBody,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<Transaction>(
    {
      url: `/api/v1/transactions/income`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: postApiV1TransactionsIncomeBody,
      signal,
    },
    options
  );
};

export const getPostApiV1TransactionsIncomeMutationOptions = <
  TError = Error | void | void | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1TransactionsIncome>>,
    TError,
    { data: PostApiV1TransactionsIncomeBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiV1TransactionsIncome>>,
  TError,
  { data: PostApiV1TransactionsIncomeBody },
  TContext
> => {
  const mutationKey = ['postApiV1TransactionsIncome'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiV1TransactionsIncome>>,
    { data: PostApiV1TransactionsIncomeBody }
  > = (props) => {
    const { data } = props ?? {};

    return postApiV1TransactionsIncome(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiV1TransactionsIncomeMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1TransactionsIncome>>
>;
export type PostApiV1TransactionsIncomeMutationBody = PostApiV1TransactionsIncomeBody;
export type PostApiV1TransactionsIncomeMutationError = Error | void | void | void;

/**
 * @summary Criar receita
 */
export const usePostApiV1TransactionsIncome = <
  TError = Error | void | void | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1TransactionsIncome>>,
    TError,
    { data: PostApiV1TransactionsIncomeBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof postApiV1TransactionsIncome>>,
  TError,
  { data: PostApiV1TransactionsIncomeBody },
  TContext
> => {
  const mutationOptions = getPostApiV1TransactionsIncomeMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Cria uma despesa fixa com bloqueio preventivo do valor no saldo disponível
 * @summary Criar despesa fixa
 */
export const postApiV1TransactionsFixedExpense = (
  postApiV1TransactionsFixedExpenseBody: PostApiV1TransactionsFixedExpenseBody,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<Transaction>(
    {
      url: `/api/v1/transactions/fixed-expense`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: postApiV1TransactionsFixedExpenseBody,
      signal,
    },
    options
  );
};

export const getPostApiV1TransactionsFixedExpenseMutationOptions = <
  TError = Error | void | void | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1TransactionsFixedExpense>>,
    TError,
    { data: PostApiV1TransactionsFixedExpenseBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiV1TransactionsFixedExpense>>,
  TError,
  { data: PostApiV1TransactionsFixedExpenseBody },
  TContext
> => {
  const mutationKey = ['postApiV1TransactionsFixedExpense'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiV1TransactionsFixedExpense>>,
    { data: PostApiV1TransactionsFixedExpenseBody }
  > = (props) => {
    const { data } = props ?? {};

    return postApiV1TransactionsFixedExpense(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiV1TransactionsFixedExpenseMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1TransactionsFixedExpense>>
>;
export type PostApiV1TransactionsFixedExpenseMutationBody = PostApiV1TransactionsFixedExpenseBody;
export type PostApiV1TransactionsFixedExpenseMutationError = Error | void | void | void;

/**
 * @summary Criar despesa fixa
 */
export const usePostApiV1TransactionsFixedExpense = <
  TError = Error | void | void | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1TransactionsFixedExpense>>,
    TError,
    { data: PostApiV1TransactionsFixedExpenseBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof postApiV1TransactionsFixedExpense>>,
  TError,
  { data: PostApiV1TransactionsFixedExpenseBody },
  TContext
> => {
  const mutationOptions = getPostApiV1TransactionsFixedExpenseMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Cria uma despesa variável com débito imediato no saldo disponível
 * @summary Criar despesa variável
 */
export const postApiV1TransactionsVariableExpense = (
  postApiV1TransactionsVariableExpenseBody: PostApiV1TransactionsVariableExpenseBody,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<Transaction>(
    {
      url: `/api/v1/transactions/variable-expense`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: postApiV1TransactionsVariableExpenseBody,
      signal,
    },
    options
  );
};

export const getPostApiV1TransactionsVariableExpenseMutationOptions = <
  TError = Error | void | void | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1TransactionsVariableExpense>>,
    TError,
    { data: PostApiV1TransactionsVariableExpenseBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiV1TransactionsVariableExpense>>,
  TError,
  { data: PostApiV1TransactionsVariableExpenseBody },
  TContext
> => {
  const mutationKey = ['postApiV1TransactionsVariableExpense'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiV1TransactionsVariableExpense>>,
    { data: PostApiV1TransactionsVariableExpenseBody }
  > = (props) => {
    const { data } = props ?? {};

    return postApiV1TransactionsVariableExpense(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiV1TransactionsVariableExpenseMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1TransactionsVariableExpense>>
>;
export type PostApiV1TransactionsVariableExpenseMutationBody =
  PostApiV1TransactionsVariableExpenseBody;
export type PostApiV1TransactionsVariableExpenseMutationError = Error | void | void | void;

/**
 * @summary Criar despesa variável
 */
export const usePostApiV1TransactionsVariableExpense = <
  TError = Error | void | void | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1TransactionsVariableExpense>>,
    TError,
    { data: PostApiV1TransactionsVariableExpenseBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof postApiV1TransactionsVariableExpense>>,
  TError,
  { data: PostApiV1TransactionsVariableExpenseBody },
  TContext
> => {
  const mutationOptions = getPostApiV1TransactionsVariableExpenseMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Lista transações do usuário com filtros opcionais (conta, tipo, status, data, categoria, paginação)
 * @summary Listar transações
 */
export const getApiV1Transactions = (
  params?: GetApiV1TransactionsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<GetApiV1Transactions200>(
    { url: `/api/v1/transactions`, method: 'GET', params, signal },
    options
  );
};

export const getGetApiV1TransactionsQueryKey = (params?: GetApiV1TransactionsParams) => {
  return [`/api/v1/transactions`, ...(params ? [params] : [])] as const;
};

export const getGetApiV1TransactionsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1Transactions>>,
  TError = void,
>(
  params?: GetApiV1TransactionsParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getApiV1Transactions>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiV1TransactionsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Transactions>>> = ({ signal }) =>
    getApiV1Transactions(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1Transactions>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetApiV1TransactionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1Transactions>>
>;
export type GetApiV1TransactionsQueryError = void;

/**
 * @summary Listar transações
 */

export function useGetApiV1Transactions<
  TData = Awaited<ReturnType<typeof getApiV1Transactions>>,
  TError = void,
>(
  params?: GetApiV1TransactionsParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getApiV1Transactions>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetApiV1TransactionsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Retorna detalhes de uma transação específica
 * @summary Obter transação por ID
 */
export const getApiV1TransactionsId = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<Transaction>(
    { url: `/api/v1/transactions/${id}`, method: 'GET', signal },
    options
  );
};

export const getGetApiV1TransactionsIdQueryKey = (id?: string) => {
  return [`/api/v1/transactions/${id}`] as const;
};

export const getGetApiV1TransactionsIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1TransactionsId>>,
  TError = void | void | void,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getApiV1TransactionsId>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiV1TransactionsIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1TransactionsId>>> = ({ signal }) =>
    getApiV1TransactionsId(id, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1TransactionsId>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetApiV1TransactionsIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1TransactionsId>>
>;
export type GetApiV1TransactionsIdQueryError = void | void | void;

/**
 * @summary Obter transação por ID
 */

export function useGetApiV1TransactionsId<
  TData = Awaited<ReturnType<typeof getApiV1TransactionsId>>,
  TError = void | void | void,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getApiV1TransactionsId>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetApiV1TransactionsIdQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Atualiza uma transação (apenas se estiver com status pending ou locked)
 * @summary Atualizar transação
 */
export const putApiV1TransactionsId = (
  id: string,
  putApiV1TransactionsIdBody: PutApiV1TransactionsIdBody,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<PutApiV1TransactionsId200>(
    {
      url: `/api/v1/transactions/${id}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: putApiV1TransactionsIdBody,
    },
    options
  );
};

export const getPutApiV1TransactionsIdMutationOptions = <
  TError = Error | void | void | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiV1TransactionsId>>,
    TError,
    { id: string; data: PutApiV1TransactionsIdBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiV1TransactionsId>>,
  TError,
  { id: string; data: PutApiV1TransactionsIdBody },
  TContext
> => {
  const mutationKey = ['putApiV1TransactionsId'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiV1TransactionsId>>,
    { id: string; data: PutApiV1TransactionsIdBody }
  > = (props) => {
    const { id, data } = props ?? {};

    return putApiV1TransactionsId(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutApiV1TransactionsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putApiV1TransactionsId>>
>;
export type PutApiV1TransactionsIdMutationBody = PutApiV1TransactionsIdBody;
export type PutApiV1TransactionsIdMutationError = Error | void | void | void;

/**
 * @summary Atualizar transação
 */
export const usePutApiV1TransactionsId = <
  TError = Error | void | void | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiV1TransactionsId>>,
    TError,
    { id: string; data: PutApiV1TransactionsIdBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof putApiV1TransactionsId>>,
  TError,
  { id: string; data: PutApiV1TransactionsIdBody },
  TContext
> => {
  const mutationOptions = getPutApiV1TransactionsIdMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Deleta uma transação (apenas se estiver com status pending ou locked)
 * @summary Deletar transação
 */
export const deleteApiV1TransactionsId = (
  id: string,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<DeleteApiV1TransactionsId200>(
    { url: `/api/v1/transactions/${id}`, method: 'DELETE' },
    options
  );
};

export const getDeleteApiV1TransactionsIdMutationOptions = <
  TError = Error | void | void | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteApiV1TransactionsId>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteApiV1TransactionsId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['deleteApiV1TransactionsId'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteApiV1TransactionsId>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteApiV1TransactionsId(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiV1TransactionsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiV1TransactionsId>>
>;

export type DeleteApiV1TransactionsIdMutationError = Error | void | void | void;

/**
 * @summary Deletar transação
 */
export const useDeleteApiV1TransactionsId = <
  TError = Error | void | void | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteApiV1TransactionsId>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteApiV1TransactionsId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeleteApiV1TransactionsIdMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Marca uma despesa fixa como paga, executando o pagamento e debitando o valor do saldo disponível
 * @summary Marcar despesa fixa como paga
 */
export const postApiV1TransactionsIdMarkAsPaid = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<PostApiV1TransactionsIdMarkAsPaid200>(
    { url: `/api/v1/transactions/${id}/mark-as-paid`, method: 'POST', signal },
    options
  );
};

export const getPostApiV1TransactionsIdMarkAsPaidMutationOptions = <
  TError = Error | void | void | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1TransactionsIdMarkAsPaid>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiV1TransactionsIdMarkAsPaid>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['postApiV1TransactionsIdMarkAsPaid'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiV1TransactionsIdMarkAsPaid>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return postApiV1TransactionsIdMarkAsPaid(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiV1TransactionsIdMarkAsPaidMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1TransactionsIdMarkAsPaid>>
>;

export type PostApiV1TransactionsIdMarkAsPaidMutationError = Error | void | void | void;

/**
 * @summary Marcar despesa fixa como paga
 */
export const usePostApiV1TransactionsIdMarkAsPaid = <
  TError = Error | void | void | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1TransactionsIdMarkAsPaid>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof postApiV1TransactionsIdMarkAsPaid>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getPostApiV1TransactionsIdMarkAsPaidMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Cria uma nova transação com os mesmos dados da transação original (com descrição modificada)
 * @summary Duplicar transação
 */
export const postApiV1TransactionsIdDuplicate = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<Transaction>(
    { url: `/api/v1/transactions/${id}/duplicate`, method: 'POST', signal },
    options
  );
};

export const getPostApiV1TransactionsIdDuplicateMutationOptions = <
  TError = Error | void | void | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1TransactionsIdDuplicate>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiV1TransactionsIdDuplicate>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['postApiV1TransactionsIdDuplicate'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiV1TransactionsIdDuplicate>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return postApiV1TransactionsIdDuplicate(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiV1TransactionsIdDuplicateMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1TransactionsIdDuplicate>>
>;

export type PostApiV1TransactionsIdDuplicateMutationError = Error | void | void | void;

/**
 * @summary Duplicar transação
 */
export const usePostApiV1TransactionsIdDuplicate = <
  TError = Error | void | void | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1TransactionsIdDuplicate>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof postApiV1TransactionsIdDuplicate>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getPostApiV1TransactionsIdDuplicateMutationOptions(options);

  return useMutation(mutationOptions);
};
