/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * BFIN API
 * Banking Finance API - Sistema de gestão financeira pessoal
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  DeleteApiV1TransactionsId200,
  Error,
  GetApiV1Transactions200,
  GetApiV1TransactionsParams,
  PostApiV1TransactionsExpenseBody,
  PostApiV1TransactionsIdMarkAsPaid200,
  PostApiV1TransactionsIncomeBody,
  PostApiV1TransactionsTransfer201,
  PostApiV1TransactionsTransferBody,
  PutApiV1TransactionsId200,
  PutApiV1TransactionsIdBody,
  Transaction,
} from '../hooks.schemas';

import { customInstance } from '../../client/custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Processa uma receita aplicando regras automáticas (30/70 - reserva de emergência e saldo disponível)
 * @summary Criar receita
 */
export type postApiV1TransactionsIncomeResponse201 = {
  data: Transaction;
  status: 201;
};

export type postApiV1TransactionsIncomeResponse400 = {
  data: Error;
  status: 400;
};

export type postApiV1TransactionsIncomeResponse401 = {
  data: void;
  status: 401;
};

export type postApiV1TransactionsIncomeResponse403 = {
  data: void;
  status: 403;
};

export type postApiV1TransactionsIncomeResponse404 = {
  data: void;
  status: 404;
};

export type postApiV1TransactionsIncomeResponseSuccess = postApiV1TransactionsIncomeResponse201 & {
  headers: Headers;
};
export type postApiV1TransactionsIncomeResponseError = (
  | postApiV1TransactionsIncomeResponse400
  | postApiV1TransactionsIncomeResponse401
  | postApiV1TransactionsIncomeResponse403
  | postApiV1TransactionsIncomeResponse404
) & {
  headers: Headers;
};

export type postApiV1TransactionsIncomeResponse =
  | postApiV1TransactionsIncomeResponseSuccess
  | postApiV1TransactionsIncomeResponseError;

export const getPostApiV1TransactionsIncomeUrl = () => {
  return `/api/v1/transactions/income`;
};

export const postApiV1TransactionsIncome = async (
  postApiV1TransactionsIncomeBody: PostApiV1TransactionsIncomeBody,
  options?: RequestInit
): Promise<postApiV1TransactionsIncomeResponse> => {
  return customInstance<postApiV1TransactionsIncomeResponse>(getPostApiV1TransactionsIncomeUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postApiV1TransactionsIncomeBody),
  });
};

export const getPostApiV1TransactionsIncomeMutationOptions = <
  TError = Error | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1TransactionsIncome>>,
    TError,
    { data: PostApiV1TransactionsIncomeBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiV1TransactionsIncome>>,
  TError,
  { data: PostApiV1TransactionsIncomeBody },
  TContext
> => {
  const mutationKey = ['postApiV1TransactionsIncome'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiV1TransactionsIncome>>,
    { data: PostApiV1TransactionsIncomeBody }
  > = (props) => {
    const { data } = props ?? {};

    return postApiV1TransactionsIncome(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiV1TransactionsIncomeMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1TransactionsIncome>>
>;
export type PostApiV1TransactionsIncomeMutationBody = PostApiV1TransactionsIncomeBody;
export type PostApiV1TransactionsIncomeMutationError = Error | void;

/**
 * @summary Criar receita
 */
export const usePostApiV1TransactionsIncome = <
  TError = Error | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1TransactionsIncome>>,
    TError,
    { data: PostApiV1TransactionsIncomeBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof postApiV1TransactionsIncome>>,
  TError,
  { data: PostApiV1TransactionsIncomeBody },
  TContext
> => {
  return useMutation(getPostApiV1TransactionsIncomeMutationOptions(options));
};
/**
 * Cria uma despesa. Tipo "fixed" bloqueia o valor no saldo (pode ser recorrente). Tipo "variable" debita imediatamente.
 * @summary Criar despesa (fixa ou variável)
 */
export type postApiV1TransactionsExpenseResponse201 = {
  data: Transaction;
  status: 201;
};

export type postApiV1TransactionsExpenseResponse400 = {
  data: Error;
  status: 400;
};

export type postApiV1TransactionsExpenseResponse401 = {
  data: void;
  status: 401;
};

export type postApiV1TransactionsExpenseResponse403 = {
  data: void;
  status: 403;
};

export type postApiV1TransactionsExpenseResponse404 = {
  data: void;
  status: 404;
};

export type postApiV1TransactionsExpenseResponseSuccess =
  postApiV1TransactionsExpenseResponse201 & {
    headers: Headers;
  };
export type postApiV1TransactionsExpenseResponseError = (
  | postApiV1TransactionsExpenseResponse400
  | postApiV1TransactionsExpenseResponse401
  | postApiV1TransactionsExpenseResponse403
  | postApiV1TransactionsExpenseResponse404
) & {
  headers: Headers;
};

export type postApiV1TransactionsExpenseResponse =
  | postApiV1TransactionsExpenseResponseSuccess
  | postApiV1TransactionsExpenseResponseError;

export const getPostApiV1TransactionsExpenseUrl = () => {
  return `/api/v1/transactions/expense`;
};

export const postApiV1TransactionsExpense = async (
  postApiV1TransactionsExpenseBody: PostApiV1TransactionsExpenseBody,
  options?: RequestInit
): Promise<postApiV1TransactionsExpenseResponse> => {
  return customInstance<postApiV1TransactionsExpenseResponse>(
    getPostApiV1TransactionsExpenseUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(postApiV1TransactionsExpenseBody),
    }
  );
};

export const getPostApiV1TransactionsExpenseMutationOptions = <
  TError = Error | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1TransactionsExpense>>,
    TError,
    { data: PostApiV1TransactionsExpenseBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiV1TransactionsExpense>>,
  TError,
  { data: PostApiV1TransactionsExpenseBody },
  TContext
> => {
  const mutationKey = ['postApiV1TransactionsExpense'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiV1TransactionsExpense>>,
    { data: PostApiV1TransactionsExpenseBody }
  > = (props) => {
    const { data } = props ?? {};

    return postApiV1TransactionsExpense(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiV1TransactionsExpenseMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1TransactionsExpense>>
>;
export type PostApiV1TransactionsExpenseMutationBody = PostApiV1TransactionsExpenseBody;
export type PostApiV1TransactionsExpenseMutationError = Error | void;

/**
 * @summary Criar despesa (fixa ou variável)
 */
export const usePostApiV1TransactionsExpense = <
  TError = Error | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1TransactionsExpense>>,
    TError,
    { data: PostApiV1TransactionsExpenseBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof postApiV1TransactionsExpense>>,
  TError,
  { data: PostApiV1TransactionsExpenseBody },
  TContext
> => {
  return useMutation(getPostApiV1TransactionsExpenseMutationOptions(options));
};
/**
 * Lista transações do usuário com filtros opcionais (conta, tipo, status, data, categoria, paginação)
 * @summary Listar transações
 */
export type getApiV1TransactionsResponse200 = {
  data: GetApiV1Transactions200;
  status: 200;
};

export type getApiV1TransactionsResponse401 = {
  data: void;
  status: 401;
};

export type getApiV1TransactionsResponseSuccess = getApiV1TransactionsResponse200 & {
  headers: Headers;
};
export type getApiV1TransactionsResponseError = getApiV1TransactionsResponse401 & {
  headers: Headers;
};

export type getApiV1TransactionsResponse =
  | getApiV1TransactionsResponseSuccess
  | getApiV1TransactionsResponseError;

export const getGetApiV1TransactionsUrl = (params?: GetApiV1TransactionsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/transactions?${stringifiedParams}`
    : `/api/v1/transactions`;
};

export const getApiV1Transactions = async (
  params?: GetApiV1TransactionsParams,
  options?: RequestInit
): Promise<getApiV1TransactionsResponse> => {
  return customInstance<getApiV1TransactionsResponse>(getGetApiV1TransactionsUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getGetApiV1TransactionsQueryKey = (params?: GetApiV1TransactionsParams) => {
  return [`/api/v1/transactions`, ...(params ? [params] : [])] as const;
};

export const getGetApiV1TransactionsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1Transactions>>,
  TError = void,
>(
  params?: GetApiV1TransactionsParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getApiV1Transactions>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiV1TransactionsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Transactions>>> = ({ signal }) =>
    getApiV1Transactions(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1Transactions>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetApiV1TransactionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1Transactions>>
>;
export type GetApiV1TransactionsQueryError = void;

/**
 * @summary Listar transações
 */

export function useGetApiV1Transactions<
  TData = Awaited<ReturnType<typeof getApiV1Transactions>>,
  TError = void,
>(
  params?: GetApiV1TransactionsParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getApiV1Transactions>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetApiV1TransactionsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Retorna detalhes de uma transação específica
 * @summary Obter transação por ID
 */
export type getApiV1TransactionsIdResponse200 = {
  data: Transaction;
  status: 200;
};

export type getApiV1TransactionsIdResponse401 = {
  data: void;
  status: 401;
};

export type getApiV1TransactionsIdResponse403 = {
  data: void;
  status: 403;
};

export type getApiV1TransactionsIdResponse404 = {
  data: void;
  status: 404;
};

export type getApiV1TransactionsIdResponseSuccess = getApiV1TransactionsIdResponse200 & {
  headers: Headers;
};
export type getApiV1TransactionsIdResponseError = (
  | getApiV1TransactionsIdResponse401
  | getApiV1TransactionsIdResponse403
  | getApiV1TransactionsIdResponse404
) & {
  headers: Headers;
};

export type getApiV1TransactionsIdResponse =
  | getApiV1TransactionsIdResponseSuccess
  | getApiV1TransactionsIdResponseError;

export const getGetApiV1TransactionsIdUrl = (id: string) => {
  return `/api/v1/transactions/${id}`;
};

export const getApiV1TransactionsId = async (
  id: string,
  options?: RequestInit
): Promise<getApiV1TransactionsIdResponse> => {
  return customInstance<getApiV1TransactionsIdResponse>(getGetApiV1TransactionsIdUrl(id), {
    ...options,
    method: 'GET',
  });
};

export const getGetApiV1TransactionsIdQueryKey = (id: string) => {
  return [`/api/v1/transactions/${id}`] as const;
};

export const getGetApiV1TransactionsIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1TransactionsId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getApiV1TransactionsId>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiV1TransactionsIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1TransactionsId>>> = ({ signal }) =>
    getApiV1TransactionsId(id, { signal, ...requestOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1TransactionsId>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetApiV1TransactionsIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1TransactionsId>>
>;
export type GetApiV1TransactionsIdQueryError = void;

/**
 * @summary Obter transação por ID
 */

export function useGetApiV1TransactionsId<
  TData = Awaited<ReturnType<typeof getApiV1TransactionsId>>,
  TError = void,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getApiV1TransactionsId>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetApiV1TransactionsIdQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Atualiza uma transação (apenas se estiver com status pending ou locked)
 * @summary Atualizar transação
 */
export type putApiV1TransactionsIdResponse200 = {
  data: PutApiV1TransactionsId200;
  status: 200;
};

export type putApiV1TransactionsIdResponse400 = {
  data: Error;
  status: 400;
};

export type putApiV1TransactionsIdResponse401 = {
  data: void;
  status: 401;
};

export type putApiV1TransactionsIdResponse403 = {
  data: void;
  status: 403;
};

export type putApiV1TransactionsIdResponse404 = {
  data: void;
  status: 404;
};

export type putApiV1TransactionsIdResponseSuccess = putApiV1TransactionsIdResponse200 & {
  headers: Headers;
};
export type putApiV1TransactionsIdResponseError = (
  | putApiV1TransactionsIdResponse400
  | putApiV1TransactionsIdResponse401
  | putApiV1TransactionsIdResponse403
  | putApiV1TransactionsIdResponse404
) & {
  headers: Headers;
};

export type putApiV1TransactionsIdResponse =
  | putApiV1TransactionsIdResponseSuccess
  | putApiV1TransactionsIdResponseError;

export const getPutApiV1TransactionsIdUrl = (id: string) => {
  return `/api/v1/transactions/${id}`;
};

export const putApiV1TransactionsId = async (
  id: string,
  putApiV1TransactionsIdBody: PutApiV1TransactionsIdBody,
  options?: RequestInit
): Promise<putApiV1TransactionsIdResponse> => {
  return customInstance<putApiV1TransactionsIdResponse>(getPutApiV1TransactionsIdUrl(id), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(putApiV1TransactionsIdBody),
  });
};

export const getPutApiV1TransactionsIdMutationOptions = <
  TError = Error | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiV1TransactionsId>>,
    TError,
    { id: string; data: PutApiV1TransactionsIdBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiV1TransactionsId>>,
  TError,
  { id: string; data: PutApiV1TransactionsIdBody },
  TContext
> => {
  const mutationKey = ['putApiV1TransactionsId'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiV1TransactionsId>>,
    { id: string; data: PutApiV1TransactionsIdBody }
  > = (props) => {
    const { id, data } = props ?? {};

    return putApiV1TransactionsId(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutApiV1TransactionsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putApiV1TransactionsId>>
>;
export type PutApiV1TransactionsIdMutationBody = PutApiV1TransactionsIdBody;
export type PutApiV1TransactionsIdMutationError = Error | void;

/**
 * @summary Atualizar transação
 */
export const usePutApiV1TransactionsId = <TError = Error | void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiV1TransactionsId>>,
    TError,
    { id: string; data: PutApiV1TransactionsIdBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof putApiV1TransactionsId>>,
  TError,
  { id: string; data: PutApiV1TransactionsIdBody },
  TContext
> => {
  return useMutation(getPutApiV1TransactionsIdMutationOptions(options));
};
/**
 * Deleta uma transação (apenas se estiver com status pending ou locked)
 * @summary Deletar transação
 */
export type deleteApiV1TransactionsIdResponse200 = {
  data: DeleteApiV1TransactionsId200;
  status: 200;
};

export type deleteApiV1TransactionsIdResponse400 = {
  data: Error;
  status: 400;
};

export type deleteApiV1TransactionsIdResponse401 = {
  data: void;
  status: 401;
};

export type deleteApiV1TransactionsIdResponse403 = {
  data: void;
  status: 403;
};

export type deleteApiV1TransactionsIdResponse404 = {
  data: void;
  status: 404;
};

export type deleteApiV1TransactionsIdResponseSuccess = deleteApiV1TransactionsIdResponse200 & {
  headers: Headers;
};
export type deleteApiV1TransactionsIdResponseError = (
  | deleteApiV1TransactionsIdResponse400
  | deleteApiV1TransactionsIdResponse401
  | deleteApiV1TransactionsIdResponse403
  | deleteApiV1TransactionsIdResponse404
) & {
  headers: Headers;
};

export type deleteApiV1TransactionsIdResponse =
  | deleteApiV1TransactionsIdResponseSuccess
  | deleteApiV1TransactionsIdResponseError;

export const getDeleteApiV1TransactionsIdUrl = (id: string) => {
  return `/api/v1/transactions/${id}`;
};

export const deleteApiV1TransactionsId = async (
  id: string,
  options?: RequestInit
): Promise<deleteApiV1TransactionsIdResponse> => {
  return customInstance<deleteApiV1TransactionsIdResponse>(getDeleteApiV1TransactionsIdUrl(id), {
    ...options,
    method: 'DELETE',
  });
};

export const getDeleteApiV1TransactionsIdMutationOptions = <
  TError = Error | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteApiV1TransactionsId>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteApiV1TransactionsId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['deleteApiV1TransactionsId'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteApiV1TransactionsId>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteApiV1TransactionsId(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiV1TransactionsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiV1TransactionsId>>
>;

export type DeleteApiV1TransactionsIdMutationError = Error | void;

/**
 * @summary Deletar transação
 */
export const useDeleteApiV1TransactionsId = <TError = Error | void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteApiV1TransactionsId>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteApiV1TransactionsId>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getDeleteApiV1TransactionsIdMutationOptions(options));
};
/**
 * Marca uma despesa fixa como paga, executando o pagamento e debitando o valor do saldo disponível
 * @summary Marcar despesa fixa como paga
 */
export type postApiV1TransactionsIdMarkAsPaidResponse200 = {
  data: PostApiV1TransactionsIdMarkAsPaid200;
  status: 200;
};

export type postApiV1TransactionsIdMarkAsPaidResponse400 = {
  data: Error;
  status: 400;
};

export type postApiV1TransactionsIdMarkAsPaidResponse401 = {
  data: void;
  status: 401;
};

export type postApiV1TransactionsIdMarkAsPaidResponse403 = {
  data: void;
  status: 403;
};

export type postApiV1TransactionsIdMarkAsPaidResponse404 = {
  data: void;
  status: 404;
};

export type postApiV1TransactionsIdMarkAsPaidResponseSuccess =
  postApiV1TransactionsIdMarkAsPaidResponse200 & {
    headers: Headers;
  };
export type postApiV1TransactionsIdMarkAsPaidResponseError = (
  | postApiV1TransactionsIdMarkAsPaidResponse400
  | postApiV1TransactionsIdMarkAsPaidResponse401
  | postApiV1TransactionsIdMarkAsPaidResponse403
  | postApiV1TransactionsIdMarkAsPaidResponse404
) & {
  headers: Headers;
};

export type postApiV1TransactionsIdMarkAsPaidResponse =
  | postApiV1TransactionsIdMarkAsPaidResponseSuccess
  | postApiV1TransactionsIdMarkAsPaidResponseError;

export const getPostApiV1TransactionsIdMarkAsPaidUrl = (id: string) => {
  return `/api/v1/transactions/${id}/mark-as-paid`;
};

export const postApiV1TransactionsIdMarkAsPaid = async (
  id: string,
  options?: RequestInit
): Promise<postApiV1TransactionsIdMarkAsPaidResponse> => {
  return customInstance<postApiV1TransactionsIdMarkAsPaidResponse>(
    getPostApiV1TransactionsIdMarkAsPaidUrl(id),
    {
      ...options,
      method: 'POST',
    }
  );
};

export const getPostApiV1TransactionsIdMarkAsPaidMutationOptions = <
  TError = Error | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1TransactionsIdMarkAsPaid>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiV1TransactionsIdMarkAsPaid>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['postApiV1TransactionsIdMarkAsPaid'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiV1TransactionsIdMarkAsPaid>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return postApiV1TransactionsIdMarkAsPaid(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiV1TransactionsIdMarkAsPaidMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1TransactionsIdMarkAsPaid>>
>;

export type PostApiV1TransactionsIdMarkAsPaidMutationError = Error | void;

/**
 * @summary Marcar despesa fixa como paga
 */
export const usePostApiV1TransactionsIdMarkAsPaid = <
  TError = Error | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1TransactionsIdMarkAsPaid>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof postApiV1TransactionsIdMarkAsPaid>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getPostApiV1TransactionsIdMarkAsPaidMutationOptions(options));
};
/**
 * Cria uma nova transação com os mesmos dados da transação original (com descrição modificada)
 * @summary Duplicar transação
 */
export type postApiV1TransactionsIdDuplicateResponse201 = {
  data: Transaction;
  status: 201;
};

export type postApiV1TransactionsIdDuplicateResponse400 = {
  data: Error;
  status: 400;
};

export type postApiV1TransactionsIdDuplicateResponse401 = {
  data: void;
  status: 401;
};

export type postApiV1TransactionsIdDuplicateResponse403 = {
  data: void;
  status: 403;
};

export type postApiV1TransactionsIdDuplicateResponse404 = {
  data: void;
  status: 404;
};

export type postApiV1TransactionsIdDuplicateResponseSuccess =
  postApiV1TransactionsIdDuplicateResponse201 & {
    headers: Headers;
  };
export type postApiV1TransactionsIdDuplicateResponseError = (
  | postApiV1TransactionsIdDuplicateResponse400
  | postApiV1TransactionsIdDuplicateResponse401
  | postApiV1TransactionsIdDuplicateResponse403
  | postApiV1TransactionsIdDuplicateResponse404
) & {
  headers: Headers;
};

export type postApiV1TransactionsIdDuplicateResponse =
  | postApiV1TransactionsIdDuplicateResponseSuccess
  | postApiV1TransactionsIdDuplicateResponseError;

export const getPostApiV1TransactionsIdDuplicateUrl = (id: string) => {
  return `/api/v1/transactions/${id}/duplicate`;
};

export const postApiV1TransactionsIdDuplicate = async (
  id: string,
  options?: RequestInit
): Promise<postApiV1TransactionsIdDuplicateResponse> => {
  return customInstance<postApiV1TransactionsIdDuplicateResponse>(
    getPostApiV1TransactionsIdDuplicateUrl(id),
    {
      ...options,
      method: 'POST',
    }
  );
};

export const getPostApiV1TransactionsIdDuplicateMutationOptions = <
  TError = Error | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1TransactionsIdDuplicate>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiV1TransactionsIdDuplicate>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['postApiV1TransactionsIdDuplicate'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiV1TransactionsIdDuplicate>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return postApiV1TransactionsIdDuplicate(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiV1TransactionsIdDuplicateMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1TransactionsIdDuplicate>>
>;

export type PostApiV1TransactionsIdDuplicateMutationError = Error | void;

/**
 * @summary Duplicar transação
 */
export const usePostApiV1TransactionsIdDuplicate = <
  TError = Error | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1TransactionsIdDuplicate>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof postApiV1TransactionsIdDuplicate>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getPostApiV1TransactionsIdDuplicateMutationOptions(options));
};
/**
 * Realiza transferência de valor da conta de origem para conta de destino. Apenas o saldo disponível (available_balance) pode ser transferido.
 * @summary Transferir valor entre contas
 */
export type postApiV1TransactionsTransferResponse201 = {
  data: PostApiV1TransactionsTransfer201;
  status: 201;
};

export type postApiV1TransactionsTransferResponse400 = {
  data: Error;
  status: 400;
};

export type postApiV1TransactionsTransferResponse401 = {
  data: void;
  status: 401;
};

export type postApiV1TransactionsTransferResponse403 = {
  data: void;
  status: 403;
};

export type postApiV1TransactionsTransferResponse404 = {
  data: void;
  status: 404;
};

export type postApiV1TransactionsTransferResponseSuccess =
  postApiV1TransactionsTransferResponse201 & {
    headers: Headers;
  };
export type postApiV1TransactionsTransferResponseError = (
  | postApiV1TransactionsTransferResponse400
  | postApiV1TransactionsTransferResponse401
  | postApiV1TransactionsTransferResponse403
  | postApiV1TransactionsTransferResponse404
) & {
  headers: Headers;
};

export type postApiV1TransactionsTransferResponse =
  | postApiV1TransactionsTransferResponseSuccess
  | postApiV1TransactionsTransferResponseError;

export const getPostApiV1TransactionsTransferUrl = () => {
  return `/api/v1/transactions/transfer`;
};

export const postApiV1TransactionsTransfer = async (
  postApiV1TransactionsTransferBody: PostApiV1TransactionsTransferBody,
  options?: RequestInit
): Promise<postApiV1TransactionsTransferResponse> => {
  return customInstance<postApiV1TransactionsTransferResponse>(
    getPostApiV1TransactionsTransferUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(postApiV1TransactionsTransferBody),
    }
  );
};

export const getPostApiV1TransactionsTransferMutationOptions = <
  TError = Error | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1TransactionsTransfer>>,
    TError,
    { data: PostApiV1TransactionsTransferBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiV1TransactionsTransfer>>,
  TError,
  { data: PostApiV1TransactionsTransferBody },
  TContext
> => {
  const mutationKey = ['postApiV1TransactionsTransfer'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiV1TransactionsTransfer>>,
    { data: PostApiV1TransactionsTransferBody }
  > = (props) => {
    const { data } = props ?? {};

    return postApiV1TransactionsTransfer(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiV1TransactionsTransferMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1TransactionsTransfer>>
>;
export type PostApiV1TransactionsTransferMutationBody = PostApiV1TransactionsTransferBody;
export type PostApiV1TransactionsTransferMutationError = Error | void;

/**
 * @summary Transferir valor entre contas
 */
export const usePostApiV1TransactionsTransfer = <
  TError = Error | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1TransactionsTransfer>>,
    TError,
    { data: PostApiV1TransactionsTransferBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof postApiV1TransactionsTransfer>>,
  TError,
  { data: PostApiV1TransactionsTransferBody },
  TContext
> => {
  return useMutation(getPostApiV1TransactionsTransferMutationOptions(options));
};
