/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * BFIN API
 * Banking Finance API - Sistema de gestão financeira pessoal
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  Error,
  GetApiV1SuggestionsDailyLimit200,
  GetApiV1SuggestionsDailyLimitParams,
} from '../hooks.schemas';

import { customInstance } from '../../client/custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Retorna o limite diário de gastos calculado para uma conta, incluindo informações sobre gastos do dia e status do limite
 * @summary Obter limite diário de gastos
 */
export type getApiV1SuggestionsDailyLimitResponse200 = {
  data: GetApiV1SuggestionsDailyLimit200;
  status: 200;
};

export type getApiV1SuggestionsDailyLimitResponse400 = {
  data: Error;
  status: 400;
};

export type getApiV1SuggestionsDailyLimitResponse401 = {
  data: void;
  status: 401;
};

export type getApiV1SuggestionsDailyLimitResponse404 = {
  data: Error;
  status: 404;
};

export type getApiV1SuggestionsDailyLimitResponse500 = {
  data: Error;
  status: 500;
};

export type getApiV1SuggestionsDailyLimitResponseSuccess =
  getApiV1SuggestionsDailyLimitResponse200 & {
    headers: Headers;
  };
export type getApiV1SuggestionsDailyLimitResponseError = (
  | getApiV1SuggestionsDailyLimitResponse400
  | getApiV1SuggestionsDailyLimitResponse401
  | getApiV1SuggestionsDailyLimitResponse404
  | getApiV1SuggestionsDailyLimitResponse500
) & {
  headers: Headers;
};

export type getApiV1SuggestionsDailyLimitResponse =
  | getApiV1SuggestionsDailyLimitResponseSuccess
  | getApiV1SuggestionsDailyLimitResponseError;

export const getGetApiV1SuggestionsDailyLimitUrl = (
  params: GetApiV1SuggestionsDailyLimitParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/suggestions/daily-limit?${stringifiedParams}`
    : `/api/v1/suggestions/daily-limit`;
};

export const getApiV1SuggestionsDailyLimit = async (
  params: GetApiV1SuggestionsDailyLimitParams,
  options?: RequestInit
): Promise<getApiV1SuggestionsDailyLimitResponse> => {
  return customInstance<getApiV1SuggestionsDailyLimitResponse>(
    getGetApiV1SuggestionsDailyLimitUrl(params),
    {
      ...options,
      method: 'GET',
    }
  );
};

export const getGetApiV1SuggestionsDailyLimitQueryKey = (
  params?: GetApiV1SuggestionsDailyLimitParams
) => {
  return [`/api/v1/suggestions/daily-limit`, ...(params ? [params] : [])] as const;
};

export const getGetApiV1SuggestionsDailyLimitQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1SuggestionsDailyLimit>>,
  TError = Error | void,
>(
  params: GetApiV1SuggestionsDailyLimitParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getApiV1SuggestionsDailyLimit>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiV1SuggestionsDailyLimitQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1SuggestionsDailyLimit>>> = ({
    signal,
  }) => getApiV1SuggestionsDailyLimit(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1SuggestionsDailyLimit>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetApiV1SuggestionsDailyLimitQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1SuggestionsDailyLimit>>
>;
export type GetApiV1SuggestionsDailyLimitQueryError = Error | void;

/**
 * @summary Obter limite diário de gastos
 */

export function useGetApiV1SuggestionsDailyLimit<
  TData = Awaited<ReturnType<typeof getApiV1SuggestionsDailyLimit>>,
  TError = Error | void,
>(
  params: GetApiV1SuggestionsDailyLimitParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getApiV1SuggestionsDailyLimit>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetApiV1SuggestionsDailyLimitQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}
