/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BFIN API
 * Banking Finance API - Sistema de gestão financeira pessoal
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  Error,
  GetApiV1SuggestionsDailyLimit200,
  GetApiV1SuggestionsDailyLimitParams,
} from '../hooks.schemas';

import { customInstance } from '../../client/custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Retorna o limite diário de gastos calculado para uma conta, incluindo informações sobre gastos do dia e status do limite
 * @summary Obter limite diário de gastos
 */
export const getApiV1SuggestionsDailyLimit = (
  params: GetApiV1SuggestionsDailyLimitParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<GetApiV1SuggestionsDailyLimit200>(
    { url: `/api/v1/suggestions/daily-limit`, method: 'GET', params, signal },
    options
  );
};

export const getGetApiV1SuggestionsDailyLimitQueryKey = (
  params?: GetApiV1SuggestionsDailyLimitParams
) => {
  return [`/api/v1/suggestions/daily-limit`, ...(params ? [params] : [])] as const;
};

export const getGetApiV1SuggestionsDailyLimitQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1SuggestionsDailyLimit>>,
  TError = Error | void | Error | Error,
>(
  params: GetApiV1SuggestionsDailyLimitParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getApiV1SuggestionsDailyLimit>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiV1SuggestionsDailyLimitQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1SuggestionsDailyLimit>>> = ({
    signal,
  }) => getApiV1SuggestionsDailyLimit(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1SuggestionsDailyLimit>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetApiV1SuggestionsDailyLimitQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1SuggestionsDailyLimit>>
>;
export type GetApiV1SuggestionsDailyLimitQueryError = Error | void | Error | Error;

/**
 * @summary Obter limite diário de gastos
 */

export function useGetApiV1SuggestionsDailyLimit<
  TData = Awaited<ReturnType<typeof getApiV1SuggestionsDailyLimit>>,
  TError = Error | void | Error | Error,
>(
  params: GetApiV1SuggestionsDailyLimitParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getApiV1SuggestionsDailyLimit>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetApiV1SuggestionsDailyLimitQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}
