/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * BFIN API
 * Banking Finance API - Sistema de gestão financeira pessoal
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  Error,
  GetApiV1InvitationsMyInvitations200Item,
  PostApiV1InvitationsTokenAccept200,
  PostApiV1InvitationsTokenReject200,
} from '../hooks.schemas';

import { customInstance } from '../../client/custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Retorna todos os convites pendentes recebidos pelo usuário logado (não expirados)
 * @summary Listar convites recebidos
 */
export type getApiV1InvitationsMyInvitationsResponse200 = {
  data: GetApiV1InvitationsMyInvitations200Item[];
  status: 200;
};

export type getApiV1InvitationsMyInvitationsResponse401 = {
  data: void;
  status: 401;
};

export type getApiV1InvitationsMyInvitationsResponseSuccess =
  getApiV1InvitationsMyInvitationsResponse200 & {
    headers: Headers;
  };
export type getApiV1InvitationsMyInvitationsResponseError =
  getApiV1InvitationsMyInvitationsResponse401 & {
    headers: Headers;
  };

export type getApiV1InvitationsMyInvitationsResponse =
  | getApiV1InvitationsMyInvitationsResponseSuccess
  | getApiV1InvitationsMyInvitationsResponseError;

export const getGetApiV1InvitationsMyInvitationsUrl = () => {
  return `/api/v1/invitations/my-invitations`;
};

export const getApiV1InvitationsMyInvitations = async (
  options?: RequestInit
): Promise<getApiV1InvitationsMyInvitationsResponse> => {
  return customInstance<getApiV1InvitationsMyInvitationsResponse>(
    getGetApiV1InvitationsMyInvitationsUrl(),
    {
      ...options,
      method: 'GET',
    }
  );
};

export const getGetApiV1InvitationsMyInvitationsQueryKey = () => {
  return [`/api/v1/invitations/my-invitations`] as const;
};

export const getGetApiV1InvitationsMyInvitationsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1InvitationsMyInvitations>>,
  TError = void,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1InvitationsMyInvitations>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiV1InvitationsMyInvitationsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1InvitationsMyInvitations>>> = ({
    signal,
  }) => getApiV1InvitationsMyInvitations({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1InvitationsMyInvitations>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetApiV1InvitationsMyInvitationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1InvitationsMyInvitations>>
>;
export type GetApiV1InvitationsMyInvitationsQueryError = void;

/**
 * @summary Listar convites recebidos
 */

export function useGetApiV1InvitationsMyInvitations<
  TData = Awaited<ReturnType<typeof getApiV1InvitationsMyInvitations>>,
  TError = void,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1InvitationsMyInvitations>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetApiV1InvitationsMyInvitationsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Aceita um convite para participar de uma conta compartilhada. O usuário deve ser o destinatário do convite e o convite deve estar pendente e não expirado.
 * @summary Aceitar convite
 */
export type postApiV1InvitationsTokenAcceptResponse200 = {
  data: PostApiV1InvitationsTokenAccept200;
  status: 200;
};

export type postApiV1InvitationsTokenAcceptResponse400 = {
  data: Error;
  status: 400;
};

export type postApiV1InvitationsTokenAcceptResponse401 = {
  data: void;
  status: 401;
};

export type postApiV1InvitationsTokenAcceptResponse403 = {
  data: Error;
  status: 403;
};

export type postApiV1InvitationsTokenAcceptResponse404 = {
  data: Error;
  status: 404;
};

export type postApiV1InvitationsTokenAcceptResponseSuccess =
  postApiV1InvitationsTokenAcceptResponse200 & {
    headers: Headers;
  };
export type postApiV1InvitationsTokenAcceptResponseError = (
  | postApiV1InvitationsTokenAcceptResponse400
  | postApiV1InvitationsTokenAcceptResponse401
  | postApiV1InvitationsTokenAcceptResponse403
  | postApiV1InvitationsTokenAcceptResponse404
) & {
  headers: Headers;
};

export type postApiV1InvitationsTokenAcceptResponse =
  | postApiV1InvitationsTokenAcceptResponseSuccess
  | postApiV1InvitationsTokenAcceptResponseError;

export const getPostApiV1InvitationsTokenAcceptUrl = (token: string) => {
  return `/api/v1/invitations/${token}/accept`;
};

export const postApiV1InvitationsTokenAccept = async (
  token: string,
  options?: RequestInit
): Promise<postApiV1InvitationsTokenAcceptResponse> => {
  return customInstance<postApiV1InvitationsTokenAcceptResponse>(
    getPostApiV1InvitationsTokenAcceptUrl(token),
    {
      ...options,
      method: 'POST',
    }
  );
};

export const getPostApiV1InvitationsTokenAcceptMutationOptions = <
  TError = Error | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1InvitationsTokenAccept>>,
    TError,
    { token: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiV1InvitationsTokenAccept>>,
  TError,
  { token: string },
  TContext
> => {
  const mutationKey = ['postApiV1InvitationsTokenAccept'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiV1InvitationsTokenAccept>>,
    { token: string }
  > = (props) => {
    const { token } = props ?? {};

    return postApiV1InvitationsTokenAccept(token, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiV1InvitationsTokenAcceptMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1InvitationsTokenAccept>>
>;

export type PostApiV1InvitationsTokenAcceptMutationError = Error | void;

/**
 * @summary Aceitar convite
 */
export const usePostApiV1InvitationsTokenAccept = <
  TError = Error | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1InvitationsTokenAccept>>,
    TError,
    { token: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof postApiV1InvitationsTokenAccept>>,
  TError,
  { token: string },
  TContext
> => {
  return useMutation(getPostApiV1InvitationsTokenAcceptMutationOptions(options));
};
/**
 * Rejeita um convite para participar de uma conta compartilhada. O usuário deve ser o destinatário do convite e o convite deve estar pendente e não expirado.
 * @summary Rejeitar convite
 */
export type postApiV1InvitationsTokenRejectResponse200 = {
  data: PostApiV1InvitationsTokenReject200;
  status: 200;
};

export type postApiV1InvitationsTokenRejectResponse400 = {
  data: Error;
  status: 400;
};

export type postApiV1InvitationsTokenRejectResponse401 = {
  data: void;
  status: 401;
};

export type postApiV1InvitationsTokenRejectResponse403 = {
  data: Error;
  status: 403;
};

export type postApiV1InvitationsTokenRejectResponse404 = {
  data: Error;
  status: 404;
};

export type postApiV1InvitationsTokenRejectResponseSuccess =
  postApiV1InvitationsTokenRejectResponse200 & {
    headers: Headers;
  };
export type postApiV1InvitationsTokenRejectResponseError = (
  | postApiV1InvitationsTokenRejectResponse400
  | postApiV1InvitationsTokenRejectResponse401
  | postApiV1InvitationsTokenRejectResponse403
  | postApiV1InvitationsTokenRejectResponse404
) & {
  headers: Headers;
};

export type postApiV1InvitationsTokenRejectResponse =
  | postApiV1InvitationsTokenRejectResponseSuccess
  | postApiV1InvitationsTokenRejectResponseError;

export const getPostApiV1InvitationsTokenRejectUrl = (token: string) => {
  return `/api/v1/invitations/${token}/reject`;
};

export const postApiV1InvitationsTokenReject = async (
  token: string,
  options?: RequestInit
): Promise<postApiV1InvitationsTokenRejectResponse> => {
  return customInstance<postApiV1InvitationsTokenRejectResponse>(
    getPostApiV1InvitationsTokenRejectUrl(token),
    {
      ...options,
      method: 'POST',
    }
  );
};

export const getPostApiV1InvitationsTokenRejectMutationOptions = <
  TError = Error | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1InvitationsTokenReject>>,
    TError,
    { token: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiV1InvitationsTokenReject>>,
  TError,
  { token: string },
  TContext
> => {
  const mutationKey = ['postApiV1InvitationsTokenReject'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiV1InvitationsTokenReject>>,
    { token: string }
  > = (props) => {
    const { token } = props ?? {};

    return postApiV1InvitationsTokenReject(token, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiV1InvitationsTokenRejectMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1InvitationsTokenReject>>
>;

export type PostApiV1InvitationsTokenRejectMutationError = Error | void;

/**
 * @summary Rejeitar convite
 */
export const usePostApiV1InvitationsTokenReject = <
  TError = Error | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1InvitationsTokenReject>>,
    TError,
    { token: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof postApiV1InvitationsTokenReject>>,
  TError,
  { token: string },
  TContext
> => {
  return useMutation(getPostApiV1InvitationsTokenRejectMutationOptions(options));
};
