/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BFIN API
 * Banking Finance API - Sistema de gestão financeira pessoal
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  Error,
  GetApiV1InvitationsMyInvitations200Item,
  PostApiV1InvitationsTokenAccept200,
  PostApiV1InvitationsTokenReject200,
} from '../hooks.schemas';

import { customInstance } from '../../client/custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Retorna todos os convites pendentes recebidos pelo usuário logado (não expirados)
 * @summary Listar convites recebidos
 */
export const getApiV1InvitationsMyInvitations = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<GetApiV1InvitationsMyInvitations200Item[]>(
    { url: `/api/v1/invitations/my-invitations`, method: 'GET', signal },
    options
  );
};

export const getGetApiV1InvitationsMyInvitationsQueryKey = () => {
  return [`/api/v1/invitations/my-invitations`] as const;
};

export const getGetApiV1InvitationsMyInvitationsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1InvitationsMyInvitations>>,
  TError = void,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1InvitationsMyInvitations>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiV1InvitationsMyInvitationsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1InvitationsMyInvitations>>> = ({
    signal,
  }) => getApiV1InvitationsMyInvitations(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1InvitationsMyInvitations>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetApiV1InvitationsMyInvitationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1InvitationsMyInvitations>>
>;
export type GetApiV1InvitationsMyInvitationsQueryError = void;

/**
 * @summary Listar convites recebidos
 */

export function useGetApiV1InvitationsMyInvitations<
  TData = Awaited<ReturnType<typeof getApiV1InvitationsMyInvitations>>,
  TError = void,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1InvitationsMyInvitations>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetApiV1InvitationsMyInvitationsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Aceita um convite para participar de uma conta compartilhada. O usuário deve ser o destinatário do convite e o convite deve estar pendente e não expirado.
 * @summary Aceitar convite
 */
export const postApiV1InvitationsTokenAccept = (
  token: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<PostApiV1InvitationsTokenAccept200>(
    { url: `/api/v1/invitations/${token}/accept`, method: 'POST', signal },
    options
  );
};

export const getPostApiV1InvitationsTokenAcceptMutationOptions = <
  TError = Error | void | Error | Error,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1InvitationsTokenAccept>>,
    TError,
    { token: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiV1InvitationsTokenAccept>>,
  TError,
  { token: string },
  TContext
> => {
  const mutationKey = ['postApiV1InvitationsTokenAccept'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiV1InvitationsTokenAccept>>,
    { token: string }
  > = (props) => {
    const { token } = props ?? {};

    return postApiV1InvitationsTokenAccept(token, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiV1InvitationsTokenAcceptMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1InvitationsTokenAccept>>
>;

export type PostApiV1InvitationsTokenAcceptMutationError = Error | void | Error | Error;

/**
 * @summary Aceitar convite
 */
export const usePostApiV1InvitationsTokenAccept = <
  TError = Error | void | Error | Error,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1InvitationsTokenAccept>>,
    TError,
    { token: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof postApiV1InvitationsTokenAccept>>,
  TError,
  { token: string },
  TContext
> => {
  const mutationOptions = getPostApiV1InvitationsTokenAcceptMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Rejeita um convite para participar de uma conta compartilhada. O usuário deve ser o destinatário do convite e o convite deve estar pendente e não expirado.
 * @summary Rejeitar convite
 */
export const postApiV1InvitationsTokenReject = (
  token: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<PostApiV1InvitationsTokenReject200>(
    { url: `/api/v1/invitations/${token}/reject`, method: 'POST', signal },
    options
  );
};

export const getPostApiV1InvitationsTokenRejectMutationOptions = <
  TError = Error | void | Error | Error,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1InvitationsTokenReject>>,
    TError,
    { token: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiV1InvitationsTokenReject>>,
  TError,
  { token: string },
  TContext
> => {
  const mutationKey = ['postApiV1InvitationsTokenReject'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiV1InvitationsTokenReject>>,
    { token: string }
  > = (props) => {
    const { token } = props ?? {};

    return postApiV1InvitationsTokenReject(token, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiV1InvitationsTokenRejectMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1InvitationsTokenReject>>
>;

export type PostApiV1InvitationsTokenRejectMutationError = Error | void | Error | Error;

/**
 * @summary Rejeitar convite
 */
export const usePostApiV1InvitationsTokenReject = <
  TError = Error | void | Error | Error,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1InvitationsTokenReject>>,
    TError,
    { token: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof postApiV1InvitationsTokenReject>>,
  TError,
  { token: string },
  TContext
> => {
  const mutationOptions = getPostApiV1InvitationsTokenRejectMutationOptions(options);

  return useMutation(mutationOptions);
};
