/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * BFIN API
 * Banking Finance API - Sistema de gestão financeira pessoal
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type { Key, SWRConfiguration } from 'swr';

import type {
  Error,
  GetApiV1SuggestionsDailyLimit200,
  GetApiV1SuggestionsDailyLimitParams,
} from '../hooks.schemas';

import { customInstance } from '../../client/custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Retorna o limite diário de gastos calculado para uma conta, incluindo informações sobre gastos do dia e status do limite
 * @summary Obter limite diário de gastos
 */
export type getApiV1SuggestionsDailyLimitResponse200 = {
  data: GetApiV1SuggestionsDailyLimit200;
  status: 200;
};

export type getApiV1SuggestionsDailyLimitResponse400 = {
  data: Error;
  status: 400;
};

export type getApiV1SuggestionsDailyLimitResponse401 = {
  data: void;
  status: 401;
};

export type getApiV1SuggestionsDailyLimitResponse404 = {
  data: Error;
  status: 404;
};

export type getApiV1SuggestionsDailyLimitResponse500 = {
  data: Error;
  status: 500;
};

export type getApiV1SuggestionsDailyLimitResponseSuccess =
  getApiV1SuggestionsDailyLimitResponse200 & {
    headers: Headers;
  };
export type getApiV1SuggestionsDailyLimitResponseError = (
  | getApiV1SuggestionsDailyLimitResponse400
  | getApiV1SuggestionsDailyLimitResponse401
  | getApiV1SuggestionsDailyLimitResponse404
  | getApiV1SuggestionsDailyLimitResponse500
) & {
  headers: Headers;
};

export type getApiV1SuggestionsDailyLimitResponse =
  | getApiV1SuggestionsDailyLimitResponseSuccess
  | getApiV1SuggestionsDailyLimitResponseError;

export const getGetApiV1SuggestionsDailyLimitUrl = (
  params: GetApiV1SuggestionsDailyLimitParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/suggestions/daily-limit?${stringifiedParams}`
    : `/api/v1/suggestions/daily-limit`;
};

export const getApiV1SuggestionsDailyLimit = async (
  params: GetApiV1SuggestionsDailyLimitParams,
  options?: RequestInit
): Promise<getApiV1SuggestionsDailyLimitResponse> => {
  return customInstance<getApiV1SuggestionsDailyLimitResponse>(
    getGetApiV1SuggestionsDailyLimitUrl(params),
    {
      ...options,
      method: 'GET',
    }
  );
};

export const getGetApiV1SuggestionsDailyLimitKey = (params: GetApiV1SuggestionsDailyLimitParams) =>
  [`/api/v1/suggestions/daily-limit`, ...(params ? [params] : [])] as const;

export type GetApiV1SuggestionsDailyLimitQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1SuggestionsDailyLimit>>
>;

/**
 * @summary Obter limite diário de gastos
 */
export const useGetApiV1SuggestionsDailyLimit = <TError = Error | void>(
  params: GetApiV1SuggestionsDailyLimitParams,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getApiV1SuggestionsDailyLimit>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetApiV1SuggestionsDailyLimitKey(params) : null));
  const swrFn = () => getApiV1SuggestionsDailyLimit(params, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
