/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * BFIN API
 * Banking Finance API - Sistema de gestão financeira pessoal
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type { Key, SWRConfiguration } from 'swr';

import type {
  Error,
  GetApiV1SuggestionsDailyLimit200,
  GetApiV1SuggestionsDailyLimitParams,
} from '../hooks.schemas';

import { customInstance } from '../../client/custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Retorna o limite diário de gastos calculado para uma conta, incluindo informações sobre gastos do dia e status do limite
 * @summary Obter limite diário de gastos
 */
export const getApiV1SuggestionsDailyLimit = (
  params: GetApiV1SuggestionsDailyLimitParams,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<GetApiV1SuggestionsDailyLimit200>(
    { url: `/api/v1/suggestions/daily-limit`, method: 'GET', params },
    options
  );
};

export const getGetApiV1SuggestionsDailyLimitKey = (params: GetApiV1SuggestionsDailyLimitParams) =>
  [`/api/v1/suggestions/daily-limit`, ...(params ? [params] : [])] as const;

export type GetApiV1SuggestionsDailyLimitQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1SuggestionsDailyLimit>>
>;
export type GetApiV1SuggestionsDailyLimitQueryError = Error | void;

/**
 * @summary Obter limite diário de gastos
 */
export const useGetApiV1SuggestionsDailyLimit = <TError = Error | void>(
  params: GetApiV1SuggestionsDailyLimitParams,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getApiV1SuggestionsDailyLimit>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetApiV1SuggestionsDailyLimitKey(params) : null));
  const swrFn = () => getApiV1SuggestionsDailyLimit(params, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
