/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * BFIN API
 * Banking Finance API - Sistema de gestão financeira pessoal
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { GetApiV1CashFlowMonthly200, GetApiV1CashFlowMonthlyParams } from '../hooks.schemas';

import { customInstance } from '../../client/custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Retorna o saldo projetado para cada dia do mês informado.

- **Mês passado**: reconstruído a partir do histórico real (balance_history)
- **Mês atual**: dias passados = histórico real, dias futuros = projeção
- **Mês futuro**: simulação completa a partir do saldo atual

**Algoritmo por dia:**
1. Aplica receitas pendentes com vencimento neste dia
2. Aplica despesas pendentes com vencimento neste dia
3. Se sobrou saldo positivo e há dívidas flutuantes:
   abate `min(saldo, dívida)` — nunca mais do que o disponível

**Dívidas flutuantes** são despesas criadas com `isFloating: true` (sem data de vencimento).
Elas aparecem em `totalFloatingDebt` e são abatidas automaticamente no dia em que
houver excedente, até zerarem.

**Receitas recorrentes** agendadas (criadas com `isRecurring: true` e data futura)
geram instâncias pendentes automaticamente e aparecem na projeção.

 * @summary Projeção de saldo mensal dia a dia
 */
export type getApiV1CashFlowMonthlyResponse200 = {
  data: GetApiV1CashFlowMonthly200;
  status: 200;
};

export type getApiV1CashFlowMonthlyResponseSuccess = getApiV1CashFlowMonthlyResponse200 & {
  headers: Headers;
};
export type getApiV1CashFlowMonthlyResponse = getApiV1CashFlowMonthlyResponseSuccess;

export const getGetApiV1CashFlowMonthlyUrl = (params: GetApiV1CashFlowMonthlyParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/cash-flow/monthly?${stringifiedParams}`
    : `/api/v1/cash-flow/monthly`;
};

export const getApiV1CashFlowMonthly = async (
  params: GetApiV1CashFlowMonthlyParams,
  options?: RequestInit
): Promise<getApiV1CashFlowMonthlyResponse> => {
  return customInstance<getApiV1CashFlowMonthlyResponse>(getGetApiV1CashFlowMonthlyUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getGetApiV1CashFlowMonthlyQueryKey = (params?: GetApiV1CashFlowMonthlyParams) => {
  return [`/api/v1/cash-flow/monthly`, ...(params ? [params] : [])] as const;
};

export const getGetApiV1CashFlowMonthlyQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1CashFlowMonthly>>,
  TError = unknown,
>(
  params: GetApiV1CashFlowMonthlyParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getApiV1CashFlowMonthly>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiV1CashFlowMonthlyQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1CashFlowMonthly>>> = ({
    signal,
  }) => getApiV1CashFlowMonthly(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1CashFlowMonthly>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetApiV1CashFlowMonthlyQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1CashFlowMonthly>>
>;
export type GetApiV1CashFlowMonthlyQueryError = unknown;

/**
 * @summary Projeção de saldo mensal dia a dia
 */

export function useGetApiV1CashFlowMonthly<
  TData = Awaited<ReturnType<typeof getApiV1CashFlowMonthly>>,
  TError = unknown,
>(
  params: GetApiV1CashFlowMonthlyParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getApiV1CashFlowMonthly>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetApiV1CashFlowMonthlyQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}
