/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * BFIN API
 * Banking Finance API - Sistema de gestão financeira pessoal
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetApiV1LoanSimulations200Item,
  GetApiV1LoanSimulationsParams,
  GetApiV1LoanSimulationsSimulationId200,
  PostApiV1LoanSimulations201,
  PostApiV1LoanSimulationsBody,
  PostApiV1LoanSimulationsIdApprove200,
  PostApiV1LoanSimulationsIdWithdraw200,
} from '../api.schemas';

import { customInstance } from '.././custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getLoanSimulations = () => {
  /**
   * @summary Criar uma simulação de empréstimo com reserva
   */
  const postApiV1LoanSimulations = (
    postApiV1LoanSimulationsBody: PostApiV1LoanSimulationsBody,
    options?: SecondParameter<typeof customInstance<PostApiV1LoanSimulations201>>
  ) => {
    return customInstance<PostApiV1LoanSimulations201>(
      {
        url: `/api/v1/loan-simulations`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: postApiV1LoanSimulationsBody,
      },
      options
    );
  };
  /**
   * Retorna lista paginada de simulações do usuário, opcionalmente filtrada por status
   * @summary Listar simulações com filtro de status
   */
  const getApiV1LoanSimulations = (
    params?: GetApiV1LoanSimulationsParams,
    options?: SecondParameter<typeof customInstance<GetApiV1LoanSimulations200Item[]>>
  ) => {
    return customInstance<GetApiV1LoanSimulations200Item[]>(
      { url: `/api/v1/loan-simulations`, method: 'GET', params },
      options
    );
  };
  /**
   * Retorna todos os detalhes incluindo plano de parcelas e informações de status
   * @summary Obter detalhes completos de uma simulação
   */
  const getApiV1LoanSimulationsSimulationId = (
    simulationId: string,
    options?: SecondParameter<typeof customInstance<GetApiV1LoanSimulationsSimulationId200>>
  ) => {
    return customInstance<GetApiV1LoanSimulationsSimulationId200>(
      { url: `/api/v1/loan-simulations/${simulationId}`, method: 'GET' },
      options
    );
  };
  /**
   * Aprova uma simulação existente, validando status PENDING, expiração de 30 dias e limite de 70% da reserva
   * @summary Aprovar uma simulação de empréstimo
   */
  const postApiV1LoanSimulationsIdApprove = (
    id: string,
    options?: SecondParameter<typeof customInstance<PostApiV1LoanSimulationsIdApprove200>>
  ) => {
    return customInstance<PostApiV1LoanSimulationsIdApprove200>(
      { url: `/api/v1/loan-simulations/${id}/approve`, method: 'POST' },
      options
    );
  };
  /**
   * Executa a retirada de fundos da reserva de emergência para o saldo disponível após aprovação da simulação
   * @summary Retirar fundos da reserva de emergência
   */
  const postApiV1LoanSimulationsIdWithdraw = (
    id: string,
    options?: SecondParameter<typeof customInstance<PostApiV1LoanSimulationsIdWithdraw200>>
  ) => {
    return customInstance<PostApiV1LoanSimulationsIdWithdraw200>(
      { url: `/api/v1/loan-simulations/${id}/withdraw`, method: 'POST' },
      options
    );
  };
  return {
    postApiV1LoanSimulations,
    getApiV1LoanSimulations,
    getApiV1LoanSimulationsSimulationId,
    postApiV1LoanSimulationsIdApprove,
    postApiV1LoanSimulationsIdWithdraw,
  };
};
export type PostApiV1LoanSimulationsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getLoanSimulations>['postApiV1LoanSimulations']>>
>;
export type GetApiV1LoanSimulationsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getLoanSimulations>['getApiV1LoanSimulations']>>
>;
export type GetApiV1LoanSimulationsSimulationIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getLoanSimulations>['getApiV1LoanSimulationsSimulationId']>>
>;
export type PostApiV1LoanSimulationsIdApproveResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getLoanSimulations>['postApiV1LoanSimulationsIdApprove']>>
>;
export type PostApiV1LoanSimulationsIdWithdrawResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getLoanSimulations>['postApiV1LoanSimulationsIdWithdraw']>>
>;
