/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * BFIN API
 * Banking Finance API - Sistema de gestão financeira pessoal
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetApiV1LoanSimulations200Item,
  GetApiV1LoanSimulationsParams,
  PostApiV1LoanSimulations201,
  PostApiV1LoanSimulationsBody,
} from '../api.schemas';

import { customInstance } from '.././custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getLoanSimulations = () => {
  /**
   * @summary Criar uma simulação de empréstimo com reserva
   */
  const postApiV1LoanSimulations = (
    postApiV1LoanSimulationsBody: PostApiV1LoanSimulationsBody,
    options?: SecondParameter<typeof customInstance<PostApiV1LoanSimulations201>>
  ) => {
    return customInstance<PostApiV1LoanSimulations201>(
      {
        url: `/api/v1/loan-simulations`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: postApiV1LoanSimulationsBody,
      },
      options
    );
  };
  /**
   * @summary Listar simulações
   */
  const getApiV1LoanSimulations = (
    params?: GetApiV1LoanSimulationsParams,
    options?: SecondParameter<typeof customInstance<GetApiV1LoanSimulations200Item[]>>
  ) => {
    return customInstance<GetApiV1LoanSimulations200Item[]>(
      { url: `/api/v1/loan-simulations`, method: 'GET', params },
      options
    );
  };
  /**
   * @summary Obter detalhes de uma simulação
   */
  const getApiV1LoanSimulationsSimulationId = (
    simulationId: string,
    options?: SecondParameter<typeof customInstance<void>>
  ) => {
    return customInstance<void>(
      { url: `/api/v1/loan-simulations/${simulationId}`, method: 'GET' },
      options
    );
  };
  return { postApiV1LoanSimulations, getApiV1LoanSimulations, getApiV1LoanSimulationsSimulationId };
};
export type PostApiV1LoanSimulationsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getLoanSimulations>['postApiV1LoanSimulations']>>
>;
export type GetApiV1LoanSimulationsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getLoanSimulations>['getApiV1LoanSimulations']>>
>;
export type GetApiV1LoanSimulationsSimulationIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getLoanSimulations>['getApiV1LoanSimulationsSimulationId']>>
>;
